// This file is auto-generated by scripts/generate-endpoint-tests.ts. Do not edit by hand.
import { describe, it, expect } from 'vitest';
import { SmartlyQ } from '../src/index';

function mockClient() {
  const calls: { method: string; path: string }[] = [];
  const fetchMock: typeof fetch = async (input, init) => {
    const url = new URL(String(input));
    calls.push({ method: init?.method ?? 'GET', path: url.pathname.replace(/^\/v1/, '') });
    return new Response(JSON.stringify({ success: true, data: {} }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  };
  const client = new SmartlyQ({ apiKey: 'sqk_test_xxxxxxxxxxxx', fetch: fetchMock, maxRetries: 0 });
  return { client, calls };
}

describe('account', () => {
  it('account.getMe -> GET /me', async () => {
    const { client, calls } = mockClient();
    await client.account.getMe();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me');
  });

  it('account.getMeUsage -> GET /me/usage', async () => {
    const { client, calls } = mockClient();
    await client.account.getMeUsage();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me/usage');
  });

  it('account.getMeBalance -> GET /me/balance', async () => {
    const { client, calls } = mockClient();
    await client.account.getMeBalance();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me/balance');
  });
});

describe('captain', () => {
  it('captain.sendMessage -> POST /captain/messages', async () => {
    const { client, calls } = mockClient();
    await client.captain.sendMessage({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/captain/messages');
  });

  it('captain.listConversations -> GET /captain/conversations', async () => {
    const { client, calls } = mockClient();
    await client.captain.listConversations();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/captain/conversations');
  });

  it('captain.getConversation -> GET /captain/conversations/{conversation_id}', async () => {
    const { client, calls } = mockClient();
    await client.captain.getConversation('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/captain/conversations/test-id');
  });
});

describe('analytics', () => {
  it('analytics.getOverview -> GET /analytics/overview', async () => {
    const { client, calls } = mockClient();
    await client.analytics.getOverview();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/overview');
  });

  it('analytics.getPosts -> GET /analytics/posts', async () => {
    const { client, calls } = mockClient();
    await client.analytics.getPosts();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/posts');
  });

  it('analytics.getAccount -> GET /analytics/accounts/{account_id}', async () => {
    const { client, calls } = mockClient();
    await client.analytics.getAccount('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/accounts/test-id');
  });

  it('analytics.dailyMetrics -> GET /analytics/daily-metrics', async () => {
    const { client, calls } = mockClient();
    await client.analytics.dailyMetrics();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/daily-metrics');
  });

  it('analytics.bestTime -> GET /analytics/best-time', async () => {
    const { client, calls } = mockClient();
    await client.analytics.bestTime();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/best-time');
  });

  it('analytics.contentDecay -> GET /analytics/content-decay', async () => {
    const { client, calls } = mockClient();
    await client.analytics.contentDecay();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/content-decay');
  });

  it('analytics.postingFrequency -> GET /analytics/posting-frequency', async () => {
    const { client, calls } = mockClient();
    await client.analytics.postingFrequency();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/posting-frequency');
  });

  it('analytics.postTimeline -> GET /analytics/posts/{post_id}/timeline', async () => {
    const { client, calls } = mockClient();
    await client.analytics.postTimeline('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/posts/test-id/timeline');
  });

  it('analytics.inboxVolume -> GET /analytics/inbox/volume', async () => {
    const { client, calls } = mockClient();
    await client.analytics.inboxVolume();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/inbox/volume');
  });

  it('analytics.inboxHeatmap -> GET /analytics/inbox/heatmap', async () => {
    const { client, calls } = mockClient();
    await client.analytics.inboxHeatmap();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/inbox/heatmap');
  });

  it('analytics.inboxSourceBreakdown -> GET /analytics/inbox/source-breakdown', async () => {
    const { client, calls } = mockClient();
    await client.analytics.inboxSourceBreakdown();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/inbox/source-breakdown');
  });

  it('analytics.inboxResponseTime -> GET /analytics/inbox/response-time', async () => {
    const { client, calls } = mockClient();
    await client.analytics.inboxResponseTime();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/inbox/response-time');
  });

  it('analytics.inboxTopAccounts -> GET /analytics/inbox/top-accounts', async () => {
    const { client, calls } = mockClient();
    await client.analytics.inboxTopAccounts();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/inbox/top-accounts');
  });

  it('analytics.inboxConversations -> GET /analytics/inbox/conversations', async () => {
    const { client, calls } = mockClient();
    await client.analytics.inboxConversations();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/inbox/conversations');
  });

  it('analytics.inboxConversationDetail -> GET /analytics/inbox/conversations/{conversation_id}', async () => {
    const { client, calls } = mockClient();
    await client.analytics.inboxConversationDetail('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/inbox/conversations/test-id');
  });
});

describe('articles', () => {
  it('articles.generate -> POST /articles/generate', async () => {
    const { client, calls } = mockClient();
    await client.articles.generate({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/articles/generate');
  });

  it('articles.list -> GET /articles', async () => {
    const { client, calls } = mockClient();
    await client.articles.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/articles');
  });

  it('articles.get -> GET /articles/{article_id}', async () => {
    const { client, calls } = mockClient();
    await client.articles.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/articles/test-id');
  });

  it('articles.delete -> DELETE /articles/{article_id}', async () => {
    const { client, calls } = mockClient();
    await client.articles.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/articles/test-id');
  });
});

describe('audio', () => {
  it('audio.textToSpeech -> POST /audio/text-to-speech', async () => {
    const { client, calls } = mockClient();
    await client.audio.textToSpeech({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/audio/text-to-speech');
  });

  it('audio.speechToText -> POST /audio/speech-to-text', async () => {
    const { client, calls } = mockClient();
    await client.audio.speechToText({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/audio/speech-to-text');
  });

  it('audio.get -> GET /audio/{audio_id}', async () => {
    const { client, calls } = mockClient();
    await client.audio.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/audio/test-id');
  });
});

describe('automations', () => {
  it('automations.list -> GET /automations', async () => {
    const { client, calls } = mockClient();
    await client.automations.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/automations');
  });

  it('automations.get -> GET /automations/{automation_id}', async () => {
    const { client, calls } = mockClient();
    await client.automations.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/automations/test-id');
  });

  it('automations.activate -> POST /automations/{automation_id}/activate', async () => {
    const { client, calls } = mockClient();
    await client.automations.activate('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/automations/test-id/activate');
  });

  it('automations.deactivate -> POST /automations/{automation_id}/deactivate', async () => {
    const { client, calls } = mockClient();
    await client.automations.deactivate('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/automations/test-id/deactivate');
  });

  it('automations.trigger -> POST /automations/{automation_id}/trigger', async () => {
    const { client, calls } = mockClient();
    await client.automations.trigger('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/automations/test-id/trigger');
  });

  it('automations.listRuns -> GET /automations/{automation_id}/runs', async () => {
    const { client, calls } = mockClient();
    await client.automations.listRuns('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/automations/test-id/runs');
  });

  it('automations.getRun -> GET /automations/{automation_id}/runs/{run_id}', async () => {
    const { client, calls } = mockClient();
    await client.automations.getRun('test-id', 'test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/automations/test-id/runs/test-id');
  });
});

describe('chatbots', () => {
  it('chatbots.list -> GET /chatbots', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots');
  });

  it('chatbots.create -> POST /chatbots', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.create({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/chatbots');
  });

  it('chatbots.get -> GET /chatbots/{id}', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id');
  });

  it('chatbots.update -> PATCH /chatbots/{id}', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.update('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/chatbots/test-id');
  });

  it('chatbots.delete -> DELETE /chatbots/{id}', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/chatbots/test-id');
  });

  it('chatbots.train -> POST /chatbots/{id}/train', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.train('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/chatbots/test-id/train');
  });

  it('chatbots.getTrainStatus -> GET /chatbots/{id}/train-status', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.getTrainStatus('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id/train-status');
  });

  it('chatbots.sendMessage -> POST /chatbots/{id}/messages', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.sendMessage('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/chatbots/test-id/messages');
  });

  it('chatbots.listConversations -> GET /chatbots/{id}/conversations', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.listConversations('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id/conversations');
  });

  it('chatbots.getConversationMessages -> GET /chatbots/{id}/conversations/{conv_id}/messages', async () => {
    const { client, calls } = mockClient();
    await client.chatbots.getConversationMessages('test-id', 'test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id/conversations/test-id/messages');
  });
});

describe('comments', () => {
  it('comments.list -> GET /social/comments', async () => {
    const { client, calls } = mockClient();
    await client.comments.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/comments');
  });

  it('comments.replyTo -> POST /social/comments/{comment_id}/reply', async () => {
    const { client, calls } = mockClient();
    await client.comments.replyTo('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/comments/test-id/reply');
  });

  it('comments.hide -> POST /social/comments/{comment_id}/hide', async () => {
    const { client, calls } = mockClient();
    await client.comments.hide('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/comments/test-id/hide');
  });

  it('comments.delete -> DELETE /social/comments/{comment_id}', async () => {
    const { client, calls } = mockClient();
    await client.comments.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/comments/test-id');
  });
});

describe('content', () => {
  it('content.rewrite -> POST /content/rewrite', async () => {
    const { client, calls } = mockClient();
    await client.content.rewrite({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/content/rewrite');
  });

  it('content.generateCaption -> POST /content/caption', async () => {
    const { client, calls } = mockClient();
    await client.content.generateCaption({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/content/caption');
  });
});

describe('crm', () => {
  it('crm.deleteContact -> DELETE /contacts/{id}', async () => {
    const { client, calls } = mockClient();
    await client.crm.deleteContact('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/contacts/test-id');
  });

  it('crm.updateCustomField -> PATCH /custom-fields/{id}', async () => {
    const { client, calls } = mockClient();
    await client.crm.updateCustomField('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/custom-fields/test-id');
  });

  it('crm.bulkImportContacts -> POST /contacts/bulk', async () => {
    const { client, calls } = mockClient();
    await client.crm.bulkImportContacts({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/bulk');
  });

  it('crm.contactChannels -> GET /contacts/{id}/channels', async () => {
    const { client, calls } = mockClient();
    await client.crm.contactChannels('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/contacts/test-id/channels');
  });
});

describe('contacts', () => {
  it('contacts.list -> GET /contacts', async () => {
    const { client, calls } = mockClient();
    await client.contacts.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/contacts');
  });

  it('contacts.create -> POST /contacts', async () => {
    const { client, calls } = mockClient();
    await client.contacts.create({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts');
  });

  it('contacts.get -> GET /contacts/{id}', async () => {
    const { client, calls } = mockClient();
    await client.contacts.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/contacts/test-id');
  });

  it('contacts.update -> PATCH /contacts/{id}', async () => {
    const { client, calls } = mockClient();
    await client.contacts.update('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/contacts/test-id');
  });

  it('contacts.addTags -> POST /contacts/{id}/tags', async () => {
    const { client, calls } = mockClient();
    await client.contacts.addTags('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/tags');
  });

  it('contacts.removeTags -> DELETE /contacts/{id}/tags', async () => {
    const { client, calls } = mockClient();
    await client.contacts.removeTags('test-id', {} as never);
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/contacts/test-id/tags');
  });

  it('contacts.listNotes -> GET /contacts/{id}/notes', async () => {
    const { client, calls } = mockClient();
    await client.contacts.listNotes('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/contacts/test-id/notes');
  });

  it('contacts.addNote -> POST /contacts/{id}/notes', async () => {
    const { client, calls } = mockClient();
    await client.contacts.addNote('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/notes');
  });

  it('contacts.enroll -> POST /contacts/{id}/enroll', async () => {
    const { client, calls } = mockClient();
    await client.contacts.enroll('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/enroll');
  });

  it('contacts.addMessage -> POST /contacts/{id}/messages', async () => {
    const { client, calls } = mockClient();
    await client.contacts.addMessage('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/messages');
  });
});

describe('customFields', () => {
  it('customFields.list -> GET /custom-fields', async () => {
    const { client, calls } = mockClient();
    await client.customFields.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/custom-fields');
  });

  it('customFields.create -> POST /custom-fields', async () => {
    const { client, calls } = mockClient();
    await client.customFields.create({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/custom-fields');
  });

  it('customFields.delete -> DELETE /custom-fields/{id}', async () => {
    const { client, calls } = mockClient();
    await client.customFields.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/custom-fields/test-id');
  });
});

describe('opportunities', () => {
  it('opportunities.listPipelines -> GET /pipelines', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.listPipelines();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/pipelines');
  });

  it('opportunities.createPipeline -> POST /pipelines', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.createPipeline({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/pipelines');
  });

  it('opportunities.list -> GET /opportunities', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/opportunities');
  });

  it('opportunities.create -> POST /opportunities', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.create({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/opportunities');
  });

  it('opportunities.get -> GET /opportunities/{id}', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/opportunities/test-id');
  });

  it('opportunities.update -> PATCH /opportunities/{id}', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.update('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/opportunities/test-id');
  });

  it('opportunities.delete -> DELETE /opportunities/{id}', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/opportunities/test-id');
  });

  it('opportunities.updateStatus -> POST /opportunities/{id}/status', async () => {
    const { client, calls } = mockClient();
    await client.opportunities.updateStatus('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/opportunities/test-id/status');
  });
});

describe('messages', () => {
  it('messages.listConversations -> GET /social/conversations', async () => {
    const { client, calls } = mockClient();
    await client.messages.listConversations();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/conversations');
  });

  it('messages.list -> GET /social/conversations/{conversation_id}/messages', async () => {
    const { client, calls } = mockClient();
    await client.messages.list('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/conversations/test-id/messages');
  });

  it('messages.send -> POST /social/conversations/{conversation_id}/messages', async () => {
    const { client, calls } = mockClient();
    await client.messages.send('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/conversations/test-id/messages');
  });

  it('messages.markConversationRead -> POST /social/conversations/{conversation_id}/read', async () => {
    const { client, calls } = mockClient();
    await client.messages.markConversationRead('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/conversations/test-id/read');
  });
});

describe('images', () => {
  it('images.generate -> POST /images/generate', async () => {
    const { client, calls } = mockClient();
    await client.images.generate({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/images/generate');
  });

  it('images.list -> GET /images', async () => {
    const { client, calls } = mockClient();
    await client.images.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/images');
  });

  it('images.get -> GET /images/{image_id}', async () => {
    const { client, calls } = mockClient();
    await client.images.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/images/test-id');
  });

  it('images.delete -> DELETE /images/{image_id}', async () => {
    const { client, calls } = mockClient();
    await client.images.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/images/test-id');
  });
});

describe('jobs', () => {
  it('jobs.list -> GET /jobs', async () => {
    const { client, calls } = mockClient();
    await client.jobs.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/jobs');
  });

  it('jobs.get -> GET /jobs/{job_id}', async () => {
    const { client, calls } = mockClient();
    await client.jobs.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/jobs/test-id');
  });

  it('jobs.cancel -> POST /jobs/{job_id}/cancel', async () => {
    const { client, calls } = mockClient();
    await client.jobs.cancel('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/jobs/test-id/cancel');
  });
});

describe('media', () => {
  it('media.list -> GET /media', async () => {
    const { client, calls } = mockClient();
    await client.media.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/media');
  });

  it('media.get -> GET /media/{media_id}', async () => {
    const { client, calls } = mockClient();
    await client.media.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/media/test-id');
  });

  it('media.delete -> DELETE /media/{media_id}', async () => {
    const { client, calls } = mockClient();
    await client.media.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/media/test-id');
  });

  it('media.getUploadUrl -> POST /media/upload-url', async () => {
    const { client, calls } = mockClient();
    await client.media.getUploadUrl({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/media/upload-url');
  });
});

describe('presentations', () => {
  it('presentations.generate -> POST /presentations/generate', async () => {
    const { client, calls } = mockClient();
    await client.presentations.generate({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/presentations/generate');
  });

  it('presentations.list -> GET /presentations', async () => {
    const { client, calls } = mockClient();
    await client.presentations.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/presentations');
  });

  it('presentations.get -> GET /presentations/{presentation_id}', async () => {
    const { client, calls } = mockClient();
    await client.presentations.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/presentations/test-id');
  });

  it('presentations.delete -> DELETE /presentations/{presentation_id}', async () => {
    const { client, calls } = mockClient();
    await client.presentations.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/presentations/test-id');
  });
});

describe('profiles', () => {
  it('profiles.list -> GET /profiles', async () => {
    const { client, calls } = mockClient();
    await client.profiles.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/profiles');
  });

  it('profiles.create -> POST /profiles', async () => {
    const { client, calls } = mockClient();
    await client.profiles.create({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles');
  });

  it('profiles.get -> GET /profiles/{id}', async () => {
    const { client, calls } = mockClient();
    await client.profiles.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/profiles/test-id');
  });

  it('profiles.delete -> DELETE /profiles/{id}', async () => {
    const { client, calls } = mockClient();
    await client.profiles.delete('test-id', {} as never);
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/profiles/test-id');
  });

  it('profiles.listAccounts -> GET /profiles/{id}/accounts', async () => {
    const { client, calls } = mockClient();
    await client.profiles.listAccounts('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/profiles/test-id/accounts');
  });

  it('profiles.pause -> POST /profiles/{id}/pause', async () => {
    const { client, calls } = mockClient();
    await client.profiles.pause('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/pause');
  });

  it('profiles.resume -> POST /profiles/{id}/resume', async () => {
    const { client, calls } = mockClient();
    await client.profiles.resume('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/resume');
  });

  it('profiles.createConnectLink -> POST /profiles/{id}/connect-link', async () => {
    const { client, calls } = mockClient();
    await client.profiles.createConnectLink('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/connect-link');
  });

  it('profiles.createConnectUrl -> POST /profiles/{id}/connect/{platform}', async () => {
    const { client, calls } = mockClient();
    await client.profiles.createConnectUrl('test-id', 'test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/connect/test-id');
  });

  it('profiles.getAccountBilling -> GET /me/account-billing', async () => {
    const { client, calls } = mockClient();
    await client.profiles.getAccountBilling();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me/account-billing');
  });
});

describe('reviews', () => {
  it('reviews.list -> GET /reviews', async () => {
    const { client, calls } = mockClient();
    await client.reviews.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/reviews');
  });

  it('reviews.replyTo -> POST /reviews/{review_id}/reply', async () => {
    const { client, calls } = mockClient();
    await client.reviews.replyTo('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/reviews/test-id/reply');
  });

  it('reviews.deleteReply -> DELETE /reviews/{review_id}/reply', async () => {
    const { client, calls } = mockClient();
    await client.reviews.deleteReply('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/reviews/test-id/reply');
  });

  it('reviews.sync -> POST /reviews/sync', async () => {
    const { client, calls } = mockClient();
    await client.reviews.sync({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/reviews/sync');
  });
});

describe('seo', () => {
  it('seo.keywordResearch -> POST /seo/keyword-research', async () => {
    const { client, calls } = mockClient();
    await client.seo.keywordResearch({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/keyword-research');
  });

  it('seo.serp -> POST /seo/serp', async () => {
    const { client, calls } = mockClient();
    await client.seo.serp({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/serp');
  });

  it('seo.keywordDifficulty -> POST /seo/keyword-difficulty', async () => {
    const { client, calls } = mockClient();
    await client.seo.keywordDifficulty({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/keyword-difficulty');
  });

  it('seo.rankedKeywords -> POST /seo/ranked-keywords', async () => {
    const { client, calls } = mockClient();
    await client.seo.rankedKeywords({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/ranked-keywords');
  });

  it('seo.domainOverview -> POST /seo/domain-overview', async () => {
    const { client, calls } = mockClient();
    await client.seo.domainOverview({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/domain-overview');
  });

  it('seo.competitors -> POST /seo/competitors', async () => {
    const { client, calls } = mockClient();
    await client.seo.competitors({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/competitors');
  });

  it('seo.backlinksSummary -> POST /seo/backlinks-summary', async () => {
    const { client, calls } = mockClient();
    await client.seo.backlinksSummary({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/backlinks-summary');
  });

  it('seo.audit -> POST /seo/audit', async () => {
    const { client, calls } = mockClient();
    await client.seo.audit({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/audit');
  });

  it('seo.backlinkProspects -> POST /seo/backlink-prospects', async () => {
    const { client, calls } = mockClient();
    await client.seo.backlinkProspects({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/backlink-prospects');
  });

  it('seo.referringDomains -> POST /seo/referring-domains', async () => {
    const { client, calls } = mockClient();
    await client.seo.referringDomains({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/referring-domains');
  });

  it('seo.backlinkAnchors -> POST /seo/backlink-anchors', async () => {
    const { client, calls } = mockClient();
    await client.seo.backlinkAnchors({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/backlink-anchors');
  });

  it('seo.spamScore -> POST /seo/spam-score', async () => {
    const { client, calls } = mockClient();
    await client.seo.spamScore({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/spam-score');
  });

  it('seo.rankHistory -> POST /seo/rank-history', async () => {
    const { client, calls } = mockClient();
    await client.seo.rankHistory({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/rank-history');
  });

  it('seo.siteAudit -> POST /seo/site-audit', async () => {
    const { client, calls } = mockClient();
    await client.seo.siteAudit({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/site-audit');
  });

  it('seo.brandLookup -> POST /seo/brand-lookup', async () => {
    const { client, calls } = mockClient();
    await client.seo.brandLookup({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/brand-lookup');
  });

  it('seo.promptExplorer -> POST /seo/prompt-explorer', async () => {
    const { client, calls } = mockClient();
    await client.seo.promptExplorer({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/prompt-explorer');
  });

  it('seo.aiAudit -> POST /seo/ai-audit', async () => {
    const { client, calls } = mockClient();
    await client.seo.aiAudit({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/ai-audit');
  });
});

describe('shorts', () => {
  it('shorts.generate -> POST /shorts/generate', async () => {
    const { client, calls } = mockClient();
    await client.shorts.generate({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/shorts/generate');
  });

  it('shorts.list -> GET /shorts', async () => {
    const { client, calls } = mockClient();
    await client.shorts.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/shorts');
  });

  it('shorts.get -> GET /shorts/{uid}', async () => {
    const { client, calls } = mockClient();
    await client.shorts.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/shorts/test-id');
  });
});

describe('social', () => {
  it('social.listAccounts -> GET /social/accounts', async () => {
    const { client, calls } = mockClient();
    await client.social.listAccounts();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts');
  });

  it('social.listPosts -> GET /social/posts', async () => {
    const { client, calls } = mockClient();
    await client.social.listPosts();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/posts');
  });

  it('social.createPost -> POST /social/posts', async () => {
    const { client, calls } = mockClient();
    await client.social.createPost({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts');
  });

  it('social.schedulePost -> POST /social/posts/schedule', async () => {
    const { client, calls } = mockClient();
    await client.social.schedulePost({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/schedule');
  });

  it('social.getPost -> GET /social/posts/{post_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.getPost('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/posts/test-id');
  });

  it('social.updatePost -> PATCH /social/posts/{post_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.updatePost('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/social/posts/test-id');
  });

  it('social.deletePost -> DELETE /social/posts/{post_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.deletePost('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/posts/test-id');
  });

  it('social.updateAccount -> PATCH /social/accounts/{account_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.updateAccount('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/social/accounts/test-id');
  });

  it('social.disconnectAccount -> DELETE /social/accounts/{account_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.disconnectAccount('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/accounts/test-id');
  });

  it('social.getAccountHealth -> GET /social/accounts/{account_id}/health', async () => {
    const { client, calls } = mockClient();
    await client.social.getAccountHealth('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/health');
  });

  it('social.getAccountReconnectUrl -> GET /social/accounts/{account_id}/reconnect-url', async () => {
    const { client, calls } = mockClient();
    await client.social.getAccountReconnectUrl('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/reconnect-url');
  });

  it('social.pauseAccount -> POST /social/accounts/{account_id}/pause', async () => {
    const { client, calls } = mockClient();
    await client.social.pauseAccount('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/pause');
  });

  it('social.resumeAccount -> POST /social/accounts/{account_id}/resume', async () => {
    const { client, calls } = mockClient();
    await client.social.resumeAccount('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/resume');
  });

  it('social.retryPost -> POST /social/posts/{post_id}/retry', async () => {
    const { client, calls } = mockClient();
    await client.social.retryPost('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/test-id/retry');
  });

  it('social.connectAccountStatus -> GET /social/connect/{platform}', async () => {
    const { client, calls } = mockClient();
    await client.social.connectAccountStatus('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/connect/test-id');
  });

  it('social.connectAccount -> POST /social/connect/{platform}', async () => {
    const { client, calls } = mockClient();
    await client.social.connectAccount('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/connect/test-id');
  });

  it('social.listQueues -> GET /social/queues', async () => {
    const { client, calls } = mockClient();
    await client.social.listQueues();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/queues');
  });

  it('social.createQueue -> POST /social/queues', async () => {
    const { client, calls } = mockClient();
    await client.social.createQueue({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/queues');
  });

  it('social.getQueue -> GET /social/queues/{queue_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.getQueue('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/queues/test-id');
  });

  it('social.updateQueue -> PUT /social/queues/{queue_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.updateQueue('test-id', {} as never);
    expect(calls[0].method).toBe('PUT');
    expect(calls[0].path).toBe('/social/queues/test-id');
  });

  it('social.deleteQueue -> DELETE /social/queues/{queue_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.deleteQueue('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/queues/test-id');
  });

  it('social.getQueueNextSlot -> GET /social/queues/{queue_id}/next-slot', async () => {
    const { client, calls } = mockClient();
    await client.social.getQueueNextSlot('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/queues/test-id/next-slot');
  });

  it('social.previewQueueSlots -> GET /social/queues/{queue_id}/preview', async () => {
    const { client, calls } = mockClient();
    await client.social.previewQueueSlots('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/queues/test-id/preview');
  });

  it('social.unpublishPost -> POST /social/posts/{post_id}/unpublish', async () => {
    const { client, calls } = mockClient();
    await client.social.unpublishPost('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/test-id/unpublish');
  });

  it('social.validatePost -> POST /social/validate/post', async () => {
    const { client, calls } = mockClient();
    await client.social.validatePost({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/validate/post');
  });

  it('social.validateMedia -> POST /social/validate/media', async () => {
    const { client, calls } = mockClient();
    await client.social.validateMedia({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/validate/media');
  });

  it('social.stopPostRecycle -> DELETE /social/posts/{post_id}/recycle', async () => {
    const { client, calls } = mockClient();
    await client.social.stopPostRecycle('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/posts/test-id/recycle');
  });

  it('social.bulkSchedulePosts -> POST /social/posts/bulk', async () => {
    const { client, calls } = mockClient();
    await client.social.bulkSchedulePosts({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/bulk');
  });

  it('social.validateBulkBatch -> POST /social/posts/bulk/validate', async () => {
    const { client, calls } = mockClient();
    await client.social.validateBulkBatch({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/bulk/validate');
  });

  it('social.bulkAccountHealth -> GET /social/accounts/health', async () => {
    const { client, calls } = mockClient();
    await client.social.bulkAccountHealth();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/health');
  });

  it('social.accountFollowerStats -> GET /social/accounts/follower-stats', async () => {
    const { client, calls } = mockClient();
    await client.social.accountFollowerStats();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/follower-stats');
  });

  it('social.tiktokCreatorInfo -> GET /social/accounts/{account_id}/tiktok/creator-info', async () => {
    const { client, calls } = mockClient();
    await client.social.tiktokCreatorInfo('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/tiktok/creator-info');
  });

  it('social.moveAccount -> POST /social/accounts/{account_id}/move', async () => {
    const { client, calls } = mockClient();
    await client.social.moveAccount('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/move');
  });

  it('social.listAccountGroups -> GET /social/account-groups', async () => {
    const { client, calls } = mockClient();
    await client.social.listAccountGroups();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/account-groups');
  });

  it('social.createAccountGroup -> POST /social/account-groups', async () => {
    const { client, calls } = mockClient();
    await client.social.createAccountGroup({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/account-groups');
  });

  it('social.getAccountGroup -> GET /social/account-groups/{group_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.getAccountGroup('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/account-groups/test-id');
  });

  it('social.updateAccountGroup -> PUT /social/account-groups/{group_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.updateAccountGroup('test-id', {} as never);
    expect(calls[0].method).toBe('PUT');
    expect(calls[0].path).toBe('/social/account-groups/test-id');
  });

  it('social.deleteAccountGroup -> DELETE /social/account-groups/{group_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.deleteAccountGroup('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/account-groups/test-id');
  });

  it('social.getConversation -> GET /social/conversations/{conversation_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.getConversation('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/conversations/test-id');
  });

  it('social.updateConversation -> PATCH /social/conversations/{conversation_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.updateConversation('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/social/conversations/test-id');
  });

  it('social.searchConversations -> GET /social/conversations/search', async () => {
    const { client, calls } = mockClient();
    await client.social.searchConversations();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/conversations/search');
  });

  it('social.pinterestBoards -> GET /social/accounts/{account_id}/pinterest/boards', async () => {
    const { client, calls } = mockClient();
    await client.social.pinterestBoards('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/pinterest/boards');
  });

  it('social.youtubePlaylists -> GET /social/accounts/{account_id}/youtube/playlists', async () => {
    const { client, calls } = mockClient();
    await client.social.youtubePlaylists('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/youtube/playlists');
  });

  it('social.instagramPublishingLimit -> GET /social/accounts/{account_id}/instagram/publishing-limit', async () => {
    const { client, calls } = mockClient();
    await client.social.instagramPublishingLimit('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/instagram/publishing-limit');
  });

  it('social.gmbPerformance -> GET /social/accounts/{account_id}/gmb/performance', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbPerformance('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/performance');
  });

  it('social.gmbSearchKeywords -> GET /social/accounts/{account_id}/gmb/search-keywords', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbSearchKeywords('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/search-keywords');
  });

  it('social.redditSearch -> GET /social/accounts/{account_id}/reddit/search', async () => {
    const { client, calls } = mockClient();
    await client.social.redditSearch('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/reddit/search');
  });

  it('social.redditFeed -> GET /social/accounts/{account_id}/reddit/feed', async () => {
    const { client, calls } = mockClient();
    await client.social.redditFeed('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/reddit/feed');
  });

  it('social.redditSubreddits -> GET /social/accounts/{account_id}/reddit/subreddits', async () => {
    const { client, calls } = mockClient();
    await client.social.redditSubreddits('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/reddit/subreddits');
  });

  it('social.redditSubredditRules -> GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}/rules', async () => {
    const { client, calls } = mockClient();
    await client.social.redditSubredditRules('test-id', 'test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/reddit/subreddits/test-id/rules');
  });

  it('social.instagramStories -> GET /social/accounts/{account_id}/instagram/stories', async () => {
    const { client, calls } = mockClient();
    await client.social.instagramStories('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/instagram/stories');
  });

  it('social.facebookPostReactions -> GET /social/accounts/{account_id}/facebook/post-reactions', async () => {
    const { client, calls } = mockClient();
    await client.social.facebookPostReactions('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/facebook/post-reactions');
  });

  it('social.instagramStoryInsights -> GET /social/accounts/{account_id}/instagram/stories/{story_id}/insights', async () => {
    const { client, calls } = mockClient();
    await client.social.instagramStoryInsights('test-id', 'test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/instagram/stories/test-id/insights');
  });

  it('social.xRetweet -> POST /social/accounts/{account_id}/x/retweets', async () => {
    const { client, calls } = mockClient();
    await client.social.xRetweet('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/x/retweets');
  });

  it('social.xUnretweet -> DELETE /social/accounts/{account_id}/x/retweets/{tweet_id}', async () => {
    const { client, calls } = mockClient();
    await client.social.xUnretweet('test-id', 'test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/accounts/test-id/x/retweets/test-id');
  });

  it('social.editPublishedPost -> POST /social/posts/{post_id}/edit', async () => {
    const { client, calls } = mockClient();
    await client.social.editPublishedPost('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/test-id/edit');
  });

  it('social.updatePostMetadata -> POST /social/posts/{post_id}/update-metadata', async () => {
    const { client, calls } = mockClient();
    await client.social.updatePostMetadata('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/test-id/update-metadata');
  });

  it('social.syncExternalPosts -> POST /social/posts/sync-external', async () => {
    const { client, calls } = mockClient();
    await client.social.syncExternalPosts({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/sync-external');
  });

  it('social.accountInsights -> GET /social/accounts/{account_id}/insights', async () => {
    const { client, calls } = mockClient();
    await client.social.accountInsights('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/insights');
  });

  it('social.gmbLocations -> GET /social/accounts/{account_id}/gmb/locations', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbLocations('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/locations');
  });

  it('social.gmbLocation -> GET /social/accounts/{account_id}/gmb/location', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbLocation('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/location');
  });

  it('social.gmbUpdateLocation -> PATCH /social/accounts/{account_id}/gmb/location', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbUpdateLocation('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/location');
  });

  it('social.gmbAttributes -> GET /social/accounts/{account_id}/gmb/attributes', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbAttributes('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/attributes');
  });

  it('social.gmbUpdateAttributes -> PUT /social/accounts/{account_id}/gmb/attributes', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbUpdateAttributes('test-id', {} as never);
    expect(calls[0].method).toBe('PUT');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/attributes');
  });

  it('social.gmbAttributeMetadata -> GET /social/accounts/{account_id}/gmb/attributes/metadata', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbAttributeMetadata('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/attributes/metadata');
  });

  it('social.gmbMedia -> GET /social/accounts/{account_id}/gmb/media', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbMedia('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/media');
  });

  it('social.gmbCreateMedia -> POST /social/accounts/{account_id}/gmb/media', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbCreateMedia('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/media');
  });

  it('social.gmbDeleteMedia -> DELETE /social/accounts/{account_id}/gmb/media', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbDeleteMedia('test-id', {} as never);
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/media');
  });

  it('social.gmbFoodMenus -> GET /social/accounts/{account_id}/gmb/food-menus', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbFoodMenus('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/food-menus');
  });

  it('social.gmbUpdateFoodMenus -> PUT /social/accounts/{account_id}/gmb/food-menus', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbUpdateFoodMenus('test-id', {} as never);
    expect(calls[0].method).toBe('PUT');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/food-menus');
  });

  it('social.gmbPlaceActions -> GET /social/accounts/{account_id}/gmb/place-actions', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbPlaceActions('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/place-actions');
  });

  it('social.gmbCreatePlaceAction -> POST /social/accounts/{account_id}/gmb/place-actions', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbCreatePlaceAction('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/place-actions');
  });

  it('social.gmbUpdatePlaceAction -> PATCH /social/accounts/{account_id}/gmb/place-actions', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbUpdatePlaceAction('test-id', {} as never);
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/place-actions');
  });

  it('social.gmbDeletePlaceAction -> DELETE /social/accounts/{account_id}/gmb/place-actions', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbDeletePlaceAction('test-id', {} as never);
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/place-actions');
  });

  it('social.gmbVerifications -> GET /social/accounts/{account_id}/gmb/verifications', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbVerifications('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/verifications');
  });

  it('social.gmbVerificationOptions -> POST /social/accounts/{account_id}/gmb/verifications/options', async () => {
    const { client, calls } = mockClient();
    await client.social.gmbVerificationOptions('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/gmb/verifications/options');
  });

  it('social.redditSubredditInfo -> GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}', async () => {
    const { client, calls } = mockClient();
    await client.social.redditSubredditInfo('test-id', 'test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/reddit/subreddits/test-id');
  });

  it('social.xMentions -> GET /social/accounts/{account_id}/x/mentions', async () => {
    const { client, calls } = mockClient();
    await client.social.xMentions('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/x/mentions');
  });
});

describe('urls', () => {
  it('urls.shorten -> POST /urls/shorten', async () => {
    const { client, calls } = mockClient();
    await client.urls.shorten({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/urls/shorten');
  });

  it('urls.list -> GET /urls', async () => {
    const { client, calls } = mockClient();
    await client.urls.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/urls');
  });

  it('urls.get -> GET /urls/{url_id}', async () => {
    const { client, calls } = mockClient();
    await client.urls.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/urls/test-id');
  });

  it('urls.delete -> DELETE /urls/{url_id}', async () => {
    const { client, calls } = mockClient();
    await client.urls.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/urls/test-id');
  });

  it('urls.getStats -> GET /urls/{url_id}/stats', async () => {
    const { client, calls } = mockClient();
    await client.urls.getStats('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/urls/test-id/stats');
  });
});

describe('videos', () => {
  it('videos.listModels -> GET /videos/models', async () => {
    const { client, calls } = mockClient();
    await client.videos.listModels();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/videos/models');
  });

  it('videos.generate -> POST /videos/generate', async () => {
    const { client, calls } = mockClient();
    await client.videos.generate({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/generate');
  });

  it('videos.list -> GET /videos', async () => {
    const { client, calls } = mockClient();
    await client.videos.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/videos');
  });

  it('videos.get -> GET /videos/{video_id}', async () => {
    const { client, calls } = mockClient();
    await client.videos.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/videos/test-id');
  });

  it('videos.delete -> DELETE /videos/{video_id}', async () => {
    const { client, calls } = mockClient();
    await client.videos.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/videos/test-id');
  });

  it('videos.generateHook -> POST /videos/hook', async () => {
    const { client, calls } = mockClient();
    await client.videos.generateHook({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/hook');
  });

  it('videos.suggestBroll -> POST /videos/broll-suggest', async () => {
    const { client, calls } = mockClient();
    await client.videos.suggestBroll({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/broll-suggest');
  });

  it('videos.suggestEmphasis -> POST /videos/emphasis', async () => {
    const { client, calls } = mockClient();
    await client.videos.suggestEmphasis({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/emphasis');
  });

  it('videos.generateViralThumbnail -> POST /videos/viral-thumbnail', async () => {
    const { client, calls } = mockClient();
    await client.videos.generateViralThumbnail({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/viral-thumbnail');
  });
});

describe('webhooks', () => {
  it('webhooks.list -> GET /webhooks', async () => {
    const { client, calls } = mockClient();
    await client.webhooks.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/webhooks');
  });

  it('webhooks.create -> POST /webhooks', async () => {
    const { client, calls } = mockClient();
    await client.webhooks.create({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/webhooks');
  });

  it('webhooks.update -> PUT /webhooks/{id}', async () => {
    const { client, calls } = mockClient();
    await client.webhooks.update('test-id', {} as never);
    expect(calls[0].method).toBe('PUT');
    expect(calls[0].path).toBe('/webhooks/test-id');
  });

  it('webhooks.delete -> DELETE /webhooks/{id}', async () => {
    const { client, calls } = mockClient();
    await client.webhooks.delete('test-id');
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/webhooks/test-id');
  });

  it('webhooks.listLogs -> GET /webhooks/logs', async () => {
    const { client, calls } = mockClient();
    await client.webhooks.listLogs();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/webhooks/logs');
  });

  it('webhooks.test -> POST /webhooks/{id}/test', async () => {
    const { client, calls } = mockClient();
    await client.webhooks.test('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/webhooks/test-id/test');
  });
});

describe('workspaces', () => {
  it('workspaces.list -> GET /workspaces', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.list();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces');
  });

  it('workspaces.create -> POST /workspaces', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.create({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces');
  });

  it('workspaces.bulkAction -> POST /workspaces/bulk', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.bulkAction({} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/bulk');
  });

  it('workspaces.get -> GET /workspaces/{id}', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.get('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces/test-id');
  });

  it('workspaces.delete -> DELETE /workspaces/{id}', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.delete('test-id', {} as never);
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/workspaces/test-id');
  });

  it('workspaces.disableSaas -> POST /workspaces/{id}/disable-saas', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.disableSaas('test-id', {} as never);
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/test-id/disable-saas');
  });

  it('workspaces.pause -> POST /workspaces/{id}/pause', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.pause('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/test-id/pause');
  });

  it('workspaces.resume -> POST /workspaces/{id}/resume', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.resume('test-id');
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/test-id/resume');
  });

  it('workspaces.getSubscription -> GET /workspaces/{id}/subscription', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.getSubscription('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces/test-id/subscription');
  });

  it('workspaces.getWallet -> GET /workspaces/{id}/wallet', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.getWallet('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces/test-id/wallet');
  });

  it('workspaces.listSaasPlans -> GET /saas/plans', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.listSaasPlans();
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/saas/plans');
  });

  it('workspaces.getSaasPlan -> GET /saas/plans/{id}', async () => {
    const { client, calls } = mockClient();
    await client.workspaces.getSaasPlan('test-id');
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/saas/plans/test-id');
  });
});
