/**
 * Generates `tests/endpoints.gen.test.ts`: one test per SDK method, calling it
 * against a mocked fetch and asserting the HTTP method + path it produces.
 * Proves the generated surface stays in lockstep with openapi.json.
 */
import { writeFileSync } from 'node:fs';
import { buildModel, type MethodSpec } from './model';

function emitTest(resourceKey: string, m: MethodSpec): string {
  const args: string[] = [];
  const expectedPath = m.path.replace(/\{[^}]+\}/g, 'test-id');
  for (let i = 0; i < m.pathParams.length; i++) args.push(`'test-id'`);
  if (m.hasBody) args.push('{} as never');
  const call = `client.${resourceKey}.${m.name}(${args.join(', ')})`;

  return [
    `  it('${resourceKey}.${m.name} -> ${m.httpMethod} ${m.path}', async () => {`,
    `    const { client, calls } = mockClient();`,
    `    await ${call};`,
    `    expect(calls[0].method).toBe('${m.httpMethod}');`,
    `    expect(calls[0].path).toBe('${expectedPath}');`,
    `  });`,
  ].join('\n');
}

const resources = buildModel();
const blocks: string[] = [];

for (const r of resources) {
  blocks.push(
    [
      `describe('${r.key}', () => {`,
      r.methods.map((m) => emitTest(r.key, m)).join('\n\n'),
      `});`,
    ].join('\n'),
  );
}

const output = [
  '// This file is auto-generated by scripts/generate-endpoint-tests.ts. Do not edit by hand.',
  "import { describe, it, expect } from 'vitest';",
  "import { SmartlyQ } from '../src/index';",
  '',
  'function mockClient() {',
  '  const calls: { method: string; path: string }[] = [];',
  '  const fetchMock: typeof fetch = async (input, init) => {',
  '    const url = new URL(String(input));',
  "    calls.push({ method: init?.method ?? 'GET', path: url.pathname.replace(/^\\/v1/, '') });",
  "    return new Response(JSON.stringify({ success: true, data: {} }), {",
  "      status: 200,",
  "      headers: { 'Content-Type': 'application/json' },",
  '    });',
  '  };',
  "  const client = new SmartlyQ({ apiKey: 'sqk_test_xxxxxxxxxxxx', fetch: fetchMock, maxRetries: 0 });",
  '  return { client, calls };',
  '}',
  '',
  blocks.join('\n\n'),
  '',
].join('\n');

writeFileSync('tests/endpoints.gen.test.ts', output);
const count = resources.reduce((n, r) => n + r.methods.length, 0);
console.log(`Generated tests/endpoints.gen.test.ts: ${count} endpoint tests.`);
