/**
 * Generates `src/resources.gen.ts` - the ergonomic resource-based SDK surface -
 * from `openapi.json`, typed against the types emitted by @hey-api/openapi-ts.
 *
 * Run via `npm run generate` (which runs openapi-ts first).
 */
import { writeFileSync } from 'node:fs';
import { buildModel, pascal, snakeToCamel, type MethodSpec } from './model';

function emitMethod(m: MethodSpec): string {
  const dataType = `t.${pascal(m.operationId)}Data`;
  // The indexed form exists for every operation; the flattened `...Response` alias does not.
  const responseType = `t.${pascal(m.operationId)}Responses[keyof t.${pascal(m.operationId)}Responses]`;
  const args: string[] = [];
  for (const p of m.pathParams) args.push(`${p.arg}: string`);
  if (m.hasBody) args.push(`body${m.bodyRequired ? '' : '?'}: ${dataType}['body']`);
  if (m.hasQuery) args.push(`query?: ${dataType}['query']`);
  args.push('options?: RequestOptions');

  const pathExpr = m.pathParams.length
    ? '`' +
      m.path.replace(/\{([^}]+)\}/g, (_, raw: string) => `\${encodeURIComponent(${snakeToCamel(raw)})}`) +
      '`'
    : `'${m.path}'`;

  const reqParts: string[] = [];
  if (m.hasBody) reqParts.push('body');
  if (m.hasQuery) reqParts.push('query');
  reqParts.push('options');

  return [
    `  /** ${m.summary.replace(/\*\//g, '*\\/')} \`${m.httpMethod} ${m.path}\` */`,
    `  ${m.name}(${args.join(', ')}): Promise<${responseType}> {`,
    `    return this._client.request('${m.httpMethod}', ${pathExpr}, { ${reqParts.join(', ')} });`,
    `  }`,
  ].join('\n');
}

const resources = buildModel();
const classes: string[] = [];
const registry: string[] = [];

for (const r of resources) {
  classes.push(
    [
      `/** ${r.tag} endpoints. */`,
      `export class ${r.className} {`,
      `  constructor(private readonly _client: CoreClient) {}`,
      '',
      r.methods.map(emitMethod).join('\n\n'),
      `}`,
    ].join('\n'),
  );
  registry.push(`    ${r.key}: new ${r.className}(client),`);
}

const output = [
  '// This file is auto-generated by scripts/generate-client.ts. Do not edit by hand.',
  "import type * as t from './generated/types.gen';",
  "import type { CoreClient, RequestOptions } from './core';",
  '',
  classes.join('\n\n'),
  '',
  'export function createResources(client: CoreClient) {',
  '  return {',
  registry.join('\n'),
  '  };',
  '}',
  '',
].join('\n');

writeFileSync('src/resources.gen.ts', output);

const opCount = resources.reduce((n, r) => n + r.methods.length, 0);
console.log(`Generated src/resources.gen.ts: ${resources.length} resources, ${opCount} methods.`);
