// This file is auto-generated by scripts/generate-client.ts. Do not edit by hand.
import type * as t from './generated/types.gen';
import type { CoreClient, RequestOptions } from './core';

/** Account endpoints. */
export class AccountResource {
  constructor(private readonly _client: CoreClient) {}

  /** Get current user profile `GET /me` */
  getMe(options?: RequestOptions): Promise<t.GetMeResponses[keyof t.GetMeResponses]> {
    return this._client.request('GET', '/me', { options });
  }

  /** Get usage summary `GET /me/usage` */
  getMeUsage(query?: t.GetMeUsageData['query'], options?: RequestOptions): Promise<t.GetMeUsageResponses[keyof t.GetMeUsageResponses]> {
    return this._client.request('GET', '/me/usage', { query, options });
  }

  /** Get wallet balance `GET /me/balance` */
  getMeBalance(options?: RequestOptions): Promise<t.GetMeBalanceResponses[keyof t.GetMeBalanceResponses]> {
    return this._client.request('GET', '/me/balance', { options });
  }
}

/** AI Captain endpoints. */
export class CaptainResource {
  constructor(private readonly _client: CoreClient) {}

  /** Send AI Captain message `POST /captain/messages` */
  sendMessage(body: t.SendCaptainMessageData['body'], options?: RequestOptions): Promise<t.SendCaptainMessageResponses[keyof t.SendCaptainMessageResponses]> {
    return this._client.request('POST', '/captain/messages', { body, options });
  }

  /** List AI Captain conversations `GET /captain/conversations` */
  listConversations(query?: t.ListCaptainConversationsData['query'], options?: RequestOptions): Promise<t.ListCaptainConversationsResponses[keyof t.ListCaptainConversationsResponses]> {
    return this._client.request('GET', '/captain/conversations', { query, options });
  }

  /** Get AI Captain conversation `GET /captain/conversations/{conversation_id}` */
  getConversation(conversationId: string, options?: RequestOptions): Promise<t.GetCaptainConversationResponses[keyof t.GetCaptainConversationResponses]> {
    return this._client.request('GET', `/captain/conversations/${encodeURIComponent(conversationId)}`, { options });
  }
}

/** Analytics endpoints. */
export class AnalyticsResource {
  constructor(private readonly _client: CoreClient) {}

  /** Get analytics overview `GET /analytics/overview` */
  getOverview(query?: t.GetAnalyticsOverviewData['query'], options?: RequestOptions): Promise<t.GetAnalyticsOverviewResponses[keyof t.GetAnalyticsOverviewResponses]> {
    return this._client.request('GET', '/analytics/overview', { query, options });
  }

  /** Get post analytics `GET /analytics/posts` */
  getPosts(query?: t.GetAnalyticsPostsData['query'], options?: RequestOptions): Promise<t.GetAnalyticsPostsResponses[keyof t.GetAnalyticsPostsResponses]> {
    return this._client.request('GET', '/analytics/posts', { query, options });
  }

  /** Get account analytics `GET /analytics/accounts/{account_id}` */
  getAccount(accountId: string, query?: t.GetAnalyticsAccountData['query'], options?: RequestOptions): Promise<t.GetAnalyticsAccountResponses[keyof t.GetAnalyticsAccountResponses]> {
    return this._client.request('GET', `/analytics/accounts/${encodeURIComponent(accountId)}`, { query, options });
  }

  /** Daily metrics `GET /analytics/daily-metrics` */
  dailyMetrics(query?: t.AnalyticsDailyMetricsData['query'], options?: RequestOptions): Promise<t.AnalyticsDailyMetricsResponses[keyof t.AnalyticsDailyMetricsResponses]> {
    return this._client.request('GET', '/analytics/daily-metrics', { query, options });
  }

  /** Best time to post `GET /analytics/best-time` */
  bestTime(query?: t.AnalyticsBestTimeData['query'], options?: RequestOptions): Promise<t.AnalyticsBestTimeResponses[keyof t.AnalyticsBestTimeResponses]> {
    return this._client.request('GET', '/analytics/best-time', { query, options });
  }

  /** Content decay `GET /analytics/content-decay` */
  contentDecay(query?: t.AnalyticsContentDecayData['query'], options?: RequestOptions): Promise<t.AnalyticsContentDecayResponses[keyof t.AnalyticsContentDecayResponses]> {
    return this._client.request('GET', '/analytics/content-decay', { query, options });
  }

  /** Posting frequency vs engagement `GET /analytics/posting-frequency` */
  postingFrequency(query?: t.AnalyticsPostingFrequencyData['query'], options?: RequestOptions): Promise<t.AnalyticsPostingFrequencyResponses[keyof t.AnalyticsPostingFrequencyResponses]> {
    return this._client.request('GET', '/analytics/posting-frequency', { query, options });
  }

  /** Post metric timeline `GET /analytics/posts/{post_id}/timeline` */
  postTimeline(postId: string, options?: RequestOptions): Promise<t.AnalyticsPostTimelineResponses[keyof t.AnalyticsPostTimelineResponses]> {
    return this._client.request('GET', `/analytics/posts/${encodeURIComponent(postId)}/timeline`, { options });
  }

  /** Inbox volume `GET /analytics/inbox/volume` */
  inboxVolume(query?: t.InboxVolumeData['query'], options?: RequestOptions): Promise<t.InboxVolumeResponses[keyof t.InboxVolumeResponses]> {
    return this._client.request('GET', '/analytics/inbox/volume', { query, options });
  }

  /** Inbox heatmap `GET /analytics/inbox/heatmap` */
  inboxHeatmap(query?: t.InboxHeatmapData['query'], options?: RequestOptions): Promise<t.InboxHeatmapResponses[keyof t.InboxHeatmapResponses]> {
    return this._client.request('GET', '/analytics/inbox/heatmap', { query, options });
  }

  /** Inbox source breakdown `GET /analytics/inbox/source-breakdown` */
  inboxSourceBreakdown(query?: t.InboxSourceBreakdownData['query'], options?: RequestOptions): Promise<t.InboxSourceBreakdownResponses[keyof t.InboxSourceBreakdownResponses]> {
    return this._client.request('GET', '/analytics/inbox/source-breakdown', { query, options });
  }

  /** Inbox response time `GET /analytics/inbox/response-time` */
  inboxResponseTime(query?: t.InboxResponseTimeData['query'], options?: RequestOptions): Promise<t.InboxResponseTimeResponses[keyof t.InboxResponseTimeResponses]> {
    return this._client.request('GET', '/analytics/inbox/response-time', { query, options });
  }

  /** Inbox top accounts `GET /analytics/inbox/top-accounts` */
  inboxTopAccounts(query?: t.InboxTopAccountsData['query'], options?: RequestOptions): Promise<t.InboxTopAccountsResponses[keyof t.InboxTopAccountsResponses]> {
    return this._client.request('GET', '/analytics/inbox/top-accounts', { query, options });
  }

  /** Inbox conversation stats `GET /analytics/inbox/conversations` */
  inboxConversations(query?: t.InboxConversationsData['query'], options?: RequestOptions): Promise<t.InboxConversationsResponses[keyof t.InboxConversationsResponses]> {
    return this._client.request('GET', '/analytics/inbox/conversations', { query, options });
  }

  /** Conversation analytics `GET /analytics/inbox/conversations/{conversation_id}` */
  inboxConversationDetail(conversationId: string, options?: RequestOptions): Promise<t.InboxConversationDetailResponses[keyof t.InboxConversationDetailResponses]> {
    return this._client.request('GET', `/analytics/inbox/conversations/${encodeURIComponent(conversationId)}`, { options });
  }
}

/** Articles endpoints. */
export class ArticlesResource {
  constructor(private readonly _client: CoreClient) {}

  /** Generate article `POST /articles/generate` */
  generate(body: t.GenerateArticleData['body'], options?: RequestOptions): Promise<t.GenerateArticleResponses[keyof t.GenerateArticleResponses]> {
    return this._client.request('POST', '/articles/generate', { body, options });
  }

  /** List articles `GET /articles` */
  list(query?: t.ListArticlesData['query'], options?: RequestOptions): Promise<t.ListArticlesResponses[keyof t.ListArticlesResponses]> {
    return this._client.request('GET', '/articles', { query, options });
  }

  /** Get article `GET /articles/{article_id}` */
  get(articleId: string, options?: RequestOptions): Promise<t.GetArticleResponses[keyof t.GetArticleResponses]> {
    return this._client.request('GET', `/articles/${encodeURIComponent(articleId)}`, { options });
  }

  /** Delete article `DELETE /articles/{article_id}` */
  delete(articleId: string, options?: RequestOptions): Promise<t.DeleteArticleResponses[keyof t.DeleteArticleResponses]> {
    return this._client.request('DELETE', `/articles/${encodeURIComponent(articleId)}`, { options });
  }
}

/** Audio endpoints. */
export class AudioResource {
  constructor(private readonly _client: CoreClient) {}

  /** Text to speech `POST /audio/text-to-speech` */
  textToSpeech(body: t.TextToSpeechData['body'], options?: RequestOptions): Promise<t.TextToSpeechResponses[keyof t.TextToSpeechResponses]> {
    return this._client.request('POST', '/audio/text-to-speech', { body, options });
  }

  /** Speech to text `POST /audio/speech-to-text` */
  speechToText(body: t.SpeechToTextData['body'], options?: RequestOptions): Promise<t.SpeechToTextResponses[keyof t.SpeechToTextResponses]> {
    return this._client.request('POST', '/audio/speech-to-text', { body, options });
  }

  /** Get audio `GET /audio/{audio_id}` */
  get(audioId: string, options?: RequestOptions): Promise<t.GetAudioResponses[keyof t.GetAudioResponses]> {
    return this._client.request('GET', `/audio/${encodeURIComponent(audioId)}`, { options });
  }
}

/** Automations endpoints. */
export class AutomationsResource {
  constructor(private readonly _client: CoreClient) {}

  /** List automations `GET /automations` */
  list(query?: t.ListAutomationsData['query'], options?: RequestOptions): Promise<t.ListAutomationsResponses[keyof t.ListAutomationsResponses]> {
    return this._client.request('GET', '/automations', { query, options });
  }

  /** Get automation `GET /automations/{automation_id}` */
  get(automationId: string, options?: RequestOptions): Promise<t.GetAutomationResponses[keyof t.GetAutomationResponses]> {
    return this._client.request('GET', `/automations/${encodeURIComponent(automationId)}`, { options });
  }

  /** Activate automation `POST /automations/{automation_id}/activate` */
  activate(automationId: string, options?: RequestOptions): Promise<t.ActivateAutomationResponses[keyof t.ActivateAutomationResponses]> {
    return this._client.request('POST', `/automations/${encodeURIComponent(automationId)}/activate`, { options });
  }

  /** Pause automation `POST /automations/{automation_id}/deactivate` */
  deactivate(automationId: string, options?: RequestOptions): Promise<t.DeactivateAutomationResponses[keyof t.DeactivateAutomationResponses]> {
    return this._client.request('POST', `/automations/${encodeURIComponent(automationId)}/deactivate`, { options });
  }

  /** Trigger automation `POST /automations/{automation_id}/trigger` */
  trigger(automationId: string, body?: t.TriggerAutomationData['body'], options?: RequestOptions): Promise<t.TriggerAutomationResponses[keyof t.TriggerAutomationResponses]> {
    return this._client.request('POST', `/automations/${encodeURIComponent(automationId)}/trigger`, { body, options });
  }

  /** List runs `GET /automations/{automation_id}/runs` */
  listRuns(automationId: string, query?: t.ListAutomationRunsData['query'], options?: RequestOptions): Promise<t.ListAutomationRunsResponses[keyof t.ListAutomationRunsResponses]> {
    return this._client.request('GET', `/automations/${encodeURIComponent(automationId)}/runs`, { query, options });
  }

  /** Get run `GET /automations/{automation_id}/runs/{run_id}` */
  getRun(automationId: string, runId: string, options?: RequestOptions): Promise<t.GetAutomationRunResponses[keyof t.GetAutomationRunResponses]> {
    return this._client.request('GET', `/automations/${encodeURIComponent(automationId)}/runs/${encodeURIComponent(runId)}`, { options });
  }
}

/** Chatbot endpoints. */
export class ChatbotsResource {
  constructor(private readonly _client: CoreClient) {}

  /** List chatbots `GET /chatbots` */
  list(query?: t.ListChatbotsData['query'], options?: RequestOptions): Promise<t.ListChatbotsResponses[keyof t.ListChatbotsResponses]> {
    return this._client.request('GET', '/chatbots', { query, options });
  }

  /** Create chatbot `POST /chatbots` */
  create(body: t.CreateChatbotData['body'], options?: RequestOptions): Promise<t.CreateChatbotResponses[keyof t.CreateChatbotResponses]> {
    return this._client.request('POST', '/chatbots', { body, options });
  }

  /** Get chatbot `GET /chatbots/{id}` */
  get(id: string, options?: RequestOptions): Promise<t.GetChatbotResponses[keyof t.GetChatbotResponses]> {
    return this._client.request('GET', `/chatbots/${encodeURIComponent(id)}`, { options });
  }

  /** Update chatbot `PATCH /chatbots/{id}` */
  update(id: string, body: t.UpdateChatbotData['body'], options?: RequestOptions): Promise<t.UpdateChatbotResponses[keyof t.UpdateChatbotResponses]> {
    return this._client.request('PATCH', `/chatbots/${encodeURIComponent(id)}`, { body, options });
  }

  /** Delete chatbot `DELETE /chatbots/{id}` */
  delete(id: string, options?: RequestOptions): Promise<t.DeleteChatbotResponses[keyof t.DeleteChatbotResponses]> {
    return this._client.request('DELETE', `/chatbots/${encodeURIComponent(id)}`, { options });
  }

  /** Start chatbot training `POST /chatbots/{id}/train` */
  train(id: string, options?: RequestOptions): Promise<t.TrainChatbotResponses[keyof t.TrainChatbotResponses]> {
    return this._client.request('POST', `/chatbots/${encodeURIComponent(id)}/train`, { options });
  }

  /** Get chatbot training status `GET /chatbots/{id}/train-status` */
  getTrainStatus(id: string, options?: RequestOptions): Promise<t.GetChatbotTrainStatusResponses[keyof t.GetChatbotTrainStatusResponses]> {
    return this._client.request('GET', `/chatbots/${encodeURIComponent(id)}/train-status`, { options });
  }

  /** Send chatbot message `POST /chatbots/{id}/messages` */
  sendMessage(id: string, body: t.SendChatbotMessageData['body'], options?: RequestOptions): Promise<t.SendChatbotMessageResponses[keyof t.SendChatbotMessageResponses]> {
    return this._client.request('POST', `/chatbots/${encodeURIComponent(id)}/messages`, { body, options });
  }

  /** List chatbot conversations `GET /chatbots/{id}/conversations` */
  listConversations(id: string, query?: t.ListChatbotConversationsData['query'], options?: RequestOptions): Promise<t.ListChatbotConversationsResponses[keyof t.ListChatbotConversationsResponses]> {
    return this._client.request('GET', `/chatbots/${encodeURIComponent(id)}/conversations`, { query, options });
  }

  /** Get conversation messages `GET /chatbots/{id}/conversations/{conv_id}/messages` */
  getConversationMessages(id: string, convId: string, options?: RequestOptions): Promise<t.GetChatbotConversationMessagesResponses[keyof t.GetChatbotConversationMessagesResponses]> {
    return this._client.request('GET', `/chatbots/${encodeURIComponent(id)}/conversations/${encodeURIComponent(convId)}/messages`, { options });
  }
}

/** Comments endpoints. */
export class CommentsResource {
  constructor(private readonly _client: CoreClient) {}

  /** List comments `GET /social/comments` */
  list(query?: t.ListCommentsData['query'], options?: RequestOptions): Promise<t.ListCommentsResponses[keyof t.ListCommentsResponses]> {
    return this._client.request('GET', '/social/comments', { query, options });
  }

  /** Reply to a comment `POST /social/comments/{comment_id}/reply` */
  replyTo(commentId: string, body: t.ReplyToCommentData['body'], options?: RequestOptions): Promise<t.ReplyToCommentResponses[keyof t.ReplyToCommentResponses]> {
    return this._client.request('POST', `/social/comments/${encodeURIComponent(commentId)}/reply`, { body, options });
  }

  /** Hide or unhide a comment `POST /social/comments/{comment_id}/hide` */
  hide(commentId: string, options?: RequestOptions): Promise<t.HideCommentResponses[keyof t.HideCommentResponses]> {
    return this._client.request('POST', `/social/comments/${encodeURIComponent(commentId)}/hide`, { options });
  }

  /** Delete a comment `DELETE /social/comments/{comment_id}` */
  delete(commentId: string, options?: RequestOptions): Promise<t.DeleteCommentResponses[keyof t.DeleteCommentResponses]> {
    return this._client.request('DELETE', `/social/comments/${encodeURIComponent(commentId)}`, { options });
  }
}

/** Content endpoints. */
export class ContentResource {
  constructor(private readonly _client: CoreClient) {}

  /** Rewrite content `POST /content/rewrite` */
  rewrite(body: t.RewriteContentData['body'], options?: RequestOptions): Promise<t.RewriteContentResponses[keyof t.RewriteContentResponses]> {
    return this._client.request('POST', '/content/rewrite', { body, options });
  }

  /** Generate a social caption `POST /content/caption` */
  generateCaption(body?: t.GenerateCaptionData['body'], options?: RequestOptions): Promise<t.GenerateCaptionResponses[keyof t.GenerateCaptionResponses]> {
    return this._client.request('POST', '/content/caption', { body, options });
  }
}

/** CRM endpoints. */
export class CrmResource {
  constructor(private readonly _client: CoreClient) {}

  /** Delete contact `DELETE /contacts/{id}` */
  deleteContact(id: string, options?: RequestOptions): Promise<t.DeleteContactResponses[keyof t.DeleteContactResponses]> {
    return this._client.request('DELETE', `/contacts/${encodeURIComponent(id)}`, { options });
  }

  /** Update custom field `PATCH /custom-fields/{id}` */
  updateCustomField(id: string, body: t.UpdateCustomFieldData['body'], options?: RequestOptions): Promise<t.UpdateCustomFieldResponses[keyof t.UpdateCustomFieldResponses]> {
    return this._client.request('PATCH', `/custom-fields/${encodeURIComponent(id)}`, { body, options });
  }

  /** Bulk import contacts `POST /contacts/bulk` */
  bulkImportContacts(body: t.BulkImportContactsData['body'], options?: RequestOptions): Promise<t.BulkImportContactsResponses[keyof t.BulkImportContactsResponses]> {
    return this._client.request('POST', '/contacts/bulk', { body, options });
  }

  /** Contact channels `GET /contacts/{id}/channels` */
  contactChannels(id: string, options?: RequestOptions): Promise<t.ContactChannelsResponses[keyof t.ContactChannelsResponses]> {
    return this._client.request('GET', `/contacts/${encodeURIComponent(id)}/channels`, { options });
  }
}

/** CRM Contacts endpoints. */
export class ContactsResource {
  constructor(private readonly _client: CoreClient) {}

  /** List contacts `GET /contacts` */
  list(query?: t.ListContactsData['query'], options?: RequestOptions): Promise<t.ListContactsResponses[keyof t.ListContactsResponses]> {
    return this._client.request('GET', '/contacts', { query, options });
  }

  /** Create or upsert a contact `POST /contacts` */
  create(body: t.CreateContactData['body'], options?: RequestOptions): Promise<t.CreateContactResponses[keyof t.CreateContactResponses]> {
    return this._client.request('POST', '/contacts', { body, options });
  }

  /** Get a contact `GET /contacts/{id}` */
  get(id: string, options?: RequestOptions): Promise<t.GetContactResponses[keyof t.GetContactResponses]> {
    return this._client.request('GET', `/contacts/${encodeURIComponent(id)}`, { options });
  }

  /** Update a contact `PATCH /contacts/{id}` */
  update(id: string, body: t.UpdateContactData['body'], options?: RequestOptions): Promise<t.UpdateContactResponses[keyof t.UpdateContactResponses]> {
    return this._client.request('PATCH', `/contacts/${encodeURIComponent(id)}`, { body, options });
  }

  /** Add tags to a contact `POST /contacts/{id}/tags` */
  addTags(id: string, body: t.AddContactTagsData['body'], options?: RequestOptions): Promise<t.AddContactTagsResponses[keyof t.AddContactTagsResponses]> {
    return this._client.request('POST', `/contacts/${encodeURIComponent(id)}/tags`, { body, options });
  }

  /** Remove tags from a contact `DELETE /contacts/{id}/tags` */
  removeTags(id: string, body: t.RemoveContactTagsData['body'], options?: RequestOptions): Promise<t.RemoveContactTagsResponses[keyof t.RemoveContactTagsResponses]> {
    return this._client.request('DELETE', `/contacts/${encodeURIComponent(id)}/tags`, { body, options });
  }

  /** List contact notes `GET /contacts/{id}/notes` */
  listNotes(id: string, options?: RequestOptions): Promise<t.ListContactNotesResponses[keyof t.ListContactNotesResponses]> {
    return this._client.request('GET', `/contacts/${encodeURIComponent(id)}/notes`, { options });
  }

  /** Add a note to a contact `POST /contacts/{id}/notes` */
  addNote(id: string, body: t.AddContactNoteData['body'], options?: RequestOptions): Promise<t.AddContactNoteResponses[keyof t.AddContactNoteResponses]> {
    return this._client.request('POST', `/contacts/${encodeURIComponent(id)}/notes`, { body, options });
  }

  /** Enroll a contact in an automation `POST /contacts/{id}/enroll` */
  enroll(id: string, body: t.EnrollContactData['body'], options?: RequestOptions): Promise<t.EnrollContactResponses[keyof t.EnrollContactResponses]> {
    return this._client.request('POST', `/contacts/${encodeURIComponent(id)}/enroll`, { body, options });
  }

  /** Log a message on a contact's timeline `POST /contacts/{id}/messages` */
  addMessage(id: string, body: t.AddContactMessageData['body'], options?: RequestOptions): Promise<t.AddContactMessageResponses[keyof t.AddContactMessageResponses]> {
    return this._client.request('POST', `/contacts/${encodeURIComponent(id)}/messages`, { body, options });
  }
}

/** CRM Custom Fields endpoints. */
export class CustomFieldsResource {
  constructor(private readonly _client: CoreClient) {}

  /** List custom fields `GET /custom-fields` */
  list(options?: RequestOptions): Promise<t.ListCustomFieldsResponses[keyof t.ListCustomFieldsResponses]> {
    return this._client.request('GET', '/custom-fields', { options });
  }

  /** Create a custom field `POST /custom-fields` */
  create(body: t.CreateCustomFieldData['body'], options?: RequestOptions): Promise<t.CreateCustomFieldResponses[keyof t.CreateCustomFieldResponses]> {
    return this._client.request('POST', '/custom-fields', { body, options });
  }

  /** Delete a custom field `DELETE /custom-fields/{id}` */
  delete(id: string, options?: RequestOptions): Promise<t.DeleteCustomFieldResponses[keyof t.DeleteCustomFieldResponses]> {
    return this._client.request('DELETE', `/custom-fields/${encodeURIComponent(id)}`, { options });
  }
}

/** CRM Opportunities endpoints. */
export class OpportunitiesResource {
  constructor(private readonly _client: CoreClient) {}

  /** List pipelines `GET /pipelines` */
  listPipelines(options?: RequestOptions): Promise<t.ListPipelinesResponses[keyof t.ListPipelinesResponses]> {
    return this._client.request('GET', '/pipelines', { options });
  }

  /** Create a pipeline `POST /pipelines` */
  createPipeline(body: t.CreatePipelineData['body'], options?: RequestOptions): Promise<t.CreatePipelineResponses[keyof t.CreatePipelineResponses]> {
    return this._client.request('POST', '/pipelines', { body, options });
  }

  /** List opportunities `GET /opportunities` */
  list(query?: t.ListOpportunitiesData['query'], options?: RequestOptions): Promise<t.ListOpportunitiesResponses[keyof t.ListOpportunitiesResponses]> {
    return this._client.request('GET', '/opportunities', { query, options });
  }

  /** Create an opportunity `POST /opportunities` */
  create(body: t.CreateOpportunityData['body'], options?: RequestOptions): Promise<t.CreateOpportunityResponses[keyof t.CreateOpportunityResponses]> {
    return this._client.request('POST', '/opportunities', { body, options });
  }

  /** Get an opportunity `GET /opportunities/{id}` */
  get(id: string, options?: RequestOptions): Promise<t.GetOpportunityResponses[keyof t.GetOpportunityResponses]> {
    return this._client.request('GET', `/opportunities/${encodeURIComponent(id)}`, { options });
  }

  /** Update an opportunity `PATCH /opportunities/{id}` */
  update(id: string, body: t.UpdateOpportunityData['body'], options?: RequestOptions): Promise<t.UpdateOpportunityResponses[keyof t.UpdateOpportunityResponses]> {
    return this._client.request('PATCH', `/opportunities/${encodeURIComponent(id)}`, { body, options });
  }

  /** Delete an opportunity `DELETE /opportunities/{id}` */
  delete(id: string, options?: RequestOptions): Promise<t.DeleteOpportunityResponses[keyof t.DeleteOpportunityResponses]> {
    return this._client.request('DELETE', `/opportunities/${encodeURIComponent(id)}`, { options });
  }

  /** Update opportunity status `POST /opportunities/{id}/status` */
  updateStatus(id: string, body: t.UpdateOpportunityStatusData['body'], options?: RequestOptions): Promise<t.UpdateOpportunityStatusResponses[keyof t.UpdateOpportunityStatusResponses]> {
    return this._client.request('POST', `/opportunities/${encodeURIComponent(id)}/status`, { body, options });
  }
}

/** Direct Messages endpoints. */
export class MessagesResource {
  constructor(private readonly _client: CoreClient) {}

  /** List DM conversations `GET /social/conversations` */
  listConversations(query?: t.ListConversationsData['query'], options?: RequestOptions): Promise<t.ListConversationsResponses[keyof t.ListConversationsResponses]> {
    return this._client.request('GET', '/social/conversations', { query, options });
  }

  /** List messages in a conversation `GET /social/conversations/{conversation_id}/messages` */
  list(conversationId: string, query?: t.ListMessagesData['query'], options?: RequestOptions): Promise<t.ListMessagesResponses[keyof t.ListMessagesResponses]> {
    return this._client.request('GET', `/social/conversations/${encodeURIComponent(conversationId)}/messages`, { query, options });
  }

  /** Send a direct message `POST /social/conversations/{conversation_id}/messages` */
  send(conversationId: string, body: t.SendDirectMessageData['body'], options?: RequestOptions): Promise<t.SendDirectMessageResponses[keyof t.SendDirectMessageResponses]> {
    return this._client.request('POST', `/social/conversations/${encodeURIComponent(conversationId)}/messages`, { body, options });
  }

  /** Mark a conversation read `POST /social/conversations/{conversation_id}/read` */
  markConversationRead(conversationId: string, options?: RequestOptions): Promise<t.MarkConversationReadResponses[keyof t.MarkConversationReadResponses]> {
    return this._client.request('POST', `/social/conversations/${encodeURIComponent(conversationId)}/read`, { options });
  }
}

/** Images endpoints. */
export class ImagesResource {
  constructor(private readonly _client: CoreClient) {}

  /** Generate image `POST /images/generate` */
  generate(body: t.GenerateImageData['body'], options?: RequestOptions): Promise<t.GenerateImageResponses[keyof t.GenerateImageResponses]> {
    return this._client.request('POST', '/images/generate', { body, options });
  }

  /** List images `GET /images` */
  list(query?: t.ListImagesData['query'], options?: RequestOptions): Promise<t.ListImagesResponses[keyof t.ListImagesResponses]> {
    return this._client.request('GET', '/images', { query, options });
  }

  /** Get image `GET /images/{image_id}` */
  get(imageId: string, options?: RequestOptions): Promise<t.GetImageResponses[keyof t.GetImageResponses]> {
    return this._client.request('GET', `/images/${encodeURIComponent(imageId)}`, { options });
  }

  /** Delete image `DELETE /images/{image_id}` */
  delete(imageId: string, options?: RequestOptions): Promise<t.DeleteImageResponses[keyof t.DeleteImageResponses]> {
    return this._client.request('DELETE', `/images/${encodeURIComponent(imageId)}`, { options });
  }
}

/** Jobs endpoints. */
export class JobsResource {
  constructor(private readonly _client: CoreClient) {}

  /** List jobs `GET /jobs` */
  list(query?: t.ListJobsData['query'], options?: RequestOptions): Promise<t.ListJobsResponses[keyof t.ListJobsResponses]> {
    return this._client.request('GET', '/jobs', { query, options });
  }

  /** Get job `GET /jobs/{job_id}` */
  get(jobId: string, options?: RequestOptions): Promise<t.GetJobResponses[keyof t.GetJobResponses]> {
    return this._client.request('GET', `/jobs/${encodeURIComponent(jobId)}`, { options });
  }

  /** Cancel job `POST /jobs/{job_id}/cancel` */
  cancel(jobId: string, body?: t.CancelJobData['body'], options?: RequestOptions): Promise<t.CancelJobResponses[keyof t.CancelJobResponses]> {
    return this._client.request('POST', `/jobs/${encodeURIComponent(jobId)}/cancel`, { body, options });
  }
}

/** Media endpoints. */
export class MediaResource {
  constructor(private readonly _client: CoreClient) {}

  /** List media `GET /media` */
  list(query?: t.ListMediaData['query'], options?: RequestOptions): Promise<t.ListMediaResponses[keyof t.ListMediaResponses]> {
    return this._client.request('GET', '/media', { query, options });
  }

  /** Get media `GET /media/{media_id}` */
  get(mediaId: string, options?: RequestOptions): Promise<t.GetMediaResponses[keyof t.GetMediaResponses]> {
    return this._client.request('GET', `/media/${encodeURIComponent(mediaId)}`, { options });
  }

  /** Delete media `DELETE /media/{media_id}` */
  delete(mediaId: string, options?: RequestOptions): Promise<t.DeleteMediaResponses[keyof t.DeleteMediaResponses]> {
    return this._client.request('DELETE', `/media/${encodeURIComponent(mediaId)}`, { options });
  }

  /** Get presigned upload URL `POST /media/upload-url` */
  getUploadUrl(body: t.GetMediaUploadUrlData['body'], options?: RequestOptions): Promise<t.GetMediaUploadUrlResponses[keyof t.GetMediaUploadUrlResponses]> {
    return this._client.request('POST', '/media/upload-url', { body, options });
  }

  /** Upload a file directly `POST /media/upload-direct` */
  uploadDirect(body: t.UploadMediaDirectData['body'], options?: RequestOptions): Promise<t.UploadMediaDirectResponses[keyof t.UploadMediaDirectResponses]> {
    return this._client.request('POST', '/media/upload-direct', { body, options });
  }
}

/** Presentations endpoints. */
export class PresentationsResource {
  constructor(private readonly _client: CoreClient) {}

  /** Generate presentation `POST /presentations/generate` */
  generate(body: t.GeneratePresentationData['body'], options?: RequestOptions): Promise<t.GeneratePresentationResponses[keyof t.GeneratePresentationResponses]> {
    return this._client.request('POST', '/presentations/generate', { body, options });
  }

  /** List presentations `GET /presentations` */
  list(query?: t.ListPresentationsData['query'], options?: RequestOptions): Promise<t.ListPresentationsResponses[keyof t.ListPresentationsResponses]> {
    return this._client.request('GET', '/presentations', { query, options });
  }

  /** Get presentation `GET /presentations/{presentation_id}` */
  get(presentationId: string, options?: RequestOptions): Promise<t.GetPresentationResponses[keyof t.GetPresentationResponses]> {
    return this._client.request('GET', `/presentations/${encodeURIComponent(presentationId)}`, { options });
  }

  /** Delete presentation `DELETE /presentations/{presentation_id}` */
  delete(presentationId: string, options?: RequestOptions): Promise<t.DeletePresentationResponses[keyof t.DeletePresentationResponses]> {
    return this._client.request('DELETE', `/presentations/${encodeURIComponent(presentationId)}`, { options });
  }
}

/** Profiles endpoints. */
export class ProfilesResource {
  constructor(private readonly _client: CoreClient) {}

  /** List profiles `GET /profiles` */
  list(query?: t.ListProfilesData['query'], options?: RequestOptions): Promise<t.ListProfilesResponses[keyof t.ListProfilesResponses]> {
    return this._client.request('GET', '/profiles', { query, options });
  }

  /** Create a profile `POST /profiles` */
  create(body: t.CreateProfileData['body'], options?: RequestOptions): Promise<t.CreateProfileResponses[keyof t.CreateProfileResponses]> {
    return this._client.request('POST', '/profiles', { body, options });
  }

  /** Get a profile `GET /profiles/{id}` */
  get(id: string, options?: RequestOptions): Promise<t.GetProfileResponses[keyof t.GetProfileResponses]> {
    return this._client.request('GET', `/profiles/${encodeURIComponent(id)}`, { options });
  }

  /** Update a profile `PATCH /profiles/{id}` */
  update(id: string, body: t.UpdateProfileData['body'], options?: RequestOptions): Promise<t.UpdateProfileResponses[keyof t.UpdateProfileResponses]> {
    return this._client.request('PATCH', `/profiles/${encodeURIComponent(id)}`, { body, options });
  }

  /** Delete a profile `DELETE /profiles/{id}` */
  delete(id: string, body: t.DeleteProfileData['body'], options?: RequestOptions): Promise<t.DeleteProfileResponses[keyof t.DeleteProfileResponses]> {
    return this._client.request('DELETE', `/profiles/${encodeURIComponent(id)}`, { body, options });
  }

  /** List a profile's connected accounts `GET /profiles/{id}/accounts` */
  listAccounts(id: string, options?: RequestOptions): Promise<t.ListProfileAccountsResponses[keyof t.ListProfileAccountsResponses]> {
    return this._client.request('GET', `/profiles/${encodeURIComponent(id)}/accounts`, { options });
  }

  /** Pause a profile `POST /profiles/{id}/pause` */
  pause(id: string, options?: RequestOptions): Promise<t.PauseProfileResponses[keyof t.PauseProfileResponses]> {
    return this._client.request('POST', `/profiles/${encodeURIComponent(id)}/pause`, { options });
  }

  /** Resume a profile `POST /profiles/{id}/resume` */
  resume(id: string, options?: RequestOptions): Promise<t.ResumeProfileResponses[keyof t.ResumeProfileResponses]> {
    return this._client.request('POST', `/profiles/${encodeURIComponent(id)}/resume`, { options });
  }

  /** Create a hosted connect link `POST /profiles/{id}/connect-link` */
  createConnectLink(id: string, body?: t.CreateProfileConnectLinkData['body'], options?: RequestOptions): Promise<t.CreateProfileConnectLinkResponses[keyof t.CreateProfileConnectLinkResponses]> {
    return this._client.request('POST', `/profiles/${encodeURIComponent(id)}/connect-link`, { body, options });
  }

  /** Get a raw connect URL for one platform `POST /profiles/{id}/connect/{platform}` */
  createConnectUrl(id: string, platform: string, body?: t.CreateProfileConnectUrlData['body'], options?: RequestOptions): Promise<t.CreateProfileConnectUrlResponses[keyof t.CreateProfileConnectUrlResponses]> {
    return this._client.request('POST', `/profiles/${encodeURIComponent(id)}/connect/${encodeURIComponent(platform)}`, { body, options });
  }

  /** Account billing summary `GET /me/account-billing` */
  getAccountBilling(options?: RequestOptions): Promise<t.GetAccountBillingResponses[keyof t.GetAccountBillingResponses]> {
    return this._client.request('GET', '/me/account-billing', { options });
  }
}

/** Reviews endpoints. */
export class ReviewsResource {
  constructor(private readonly _client: CoreClient) {}

  /** List reviews `GET /reviews` */
  list(query?: t.ListReviewsData['query'], options?: RequestOptions): Promise<t.ListReviewsResponses[keyof t.ListReviewsResponses]> {
    return this._client.request('GET', '/reviews', { query, options });
  }

  /** Reply to review `POST /reviews/{review_id}/reply` */
  replyTo(reviewId: string, body: t.ReplyToReviewData['body'], options?: RequestOptions): Promise<t.ReplyToReviewResponses[keyof t.ReplyToReviewResponses]> {
    return this._client.request('POST', `/reviews/${encodeURIComponent(reviewId)}/reply`, { body, options });
  }

  /** Delete review reply `DELETE /reviews/{review_id}/reply` */
  deleteReply(reviewId: string, options?: RequestOptions): Promise<t.DeleteReviewReplyResponses[keyof t.DeleteReviewReplyResponses]> {
    return this._client.request('DELETE', `/reviews/${encodeURIComponent(reviewId)}/reply`, { options });
  }

  /** Sync reviews `POST /reviews/sync` */
  sync(body?: t.SyncReviewsData['body'], options?: RequestOptions): Promise<t.SyncReviewsResponses[keyof t.SyncReviewsResponses]> {
    return this._client.request('POST', '/reviews/sync', { body, options });
  }
}

/** SEO endpoints. */
export class SeoResource {
  constructor(private readonly _client: CoreClient) {}

  /** Keyword research `POST /seo/keyword-research` */
  keywordResearch(body: t.SeoKeywordResearchData['body'], options?: RequestOptions): Promise<t.SeoKeywordResearchResponses[keyof t.SeoKeywordResearchResponses]> {
    return this._client.request('POST', '/seo/keyword-research', { body, options });
  }

  /** Live SERP lookup `POST /seo/serp` */
  serp(body: t.SeoSerpData['body'], options?: RequestOptions): Promise<t.SeoSerpResponses[keyof t.SeoSerpResponses]> {
    return this._client.request('POST', '/seo/serp', { body, options });
  }

  /** Keyword difficulty `POST /seo/keyword-difficulty` */
  keywordDifficulty(body: t.SeoKeywordDifficultyData['body'], options?: RequestOptions): Promise<t.SeoKeywordDifficultyResponses[keyof t.SeoKeywordDifficultyResponses]> {
    return this._client.request('POST', '/seo/keyword-difficulty', { body, options });
  }

  /** Ranked keywords (rank tracking) `POST /seo/ranked-keywords` */
  rankedKeywords(body: t.SeoRankedKeywordsData['body'], options?: RequestOptions): Promise<t.SeoRankedKeywordsResponses[keyof t.SeoRankedKeywordsResponses]> {
    return this._client.request('POST', '/seo/ranked-keywords', { body, options });
  }

  /** Domain rank overview `POST /seo/domain-overview` */
  domainOverview(body: t.SeoDomainOverviewData['body'], options?: RequestOptions): Promise<t.SeoDomainOverviewResponses[keyof t.SeoDomainOverviewResponses]> {
    return this._client.request('POST', '/seo/domain-overview', { body, options });
  }

  /** Organic competitors `POST /seo/competitors` */
  competitors(body: t.SeoCompetitorsData['body'], options?: RequestOptions): Promise<t.SeoCompetitorsResponses[keyof t.SeoCompetitorsResponses]> {
    return this._client.request('POST', '/seo/competitors', { body, options });
  }

  /** Backlink profile summary `POST /seo/backlinks-summary` */
  backlinksSummary(body: t.SeoBacklinksSummaryData['body'], options?: RequestOptions): Promise<t.SeoBacklinksSummaryResponses[keyof t.SeoBacklinksSummaryResponses]> {
    return this._client.request('POST', '/seo/backlinks-summary', { body, options });
  }

  /** On-page SEO audit `POST /seo/audit` */
  audit(body: t.SeoAuditData['body'], options?: RequestOptions): Promise<t.SeoAuditResponses[keyof t.SeoAuditResponses]> {
    return this._client.request('POST', '/seo/audit', { body, options });
  }

  /** Backlink prospects (link gap) `POST /seo/backlink-prospects` */
  backlinkProspects(body: t.SeoBacklinkProspectsData['body'], options?: RequestOptions): Promise<t.SeoBacklinkProspectsResponses[keyof t.SeoBacklinkProspectsResponses]> {
    return this._client.request('POST', '/seo/backlink-prospects', { body, options });
  }

  /** Referring domains `POST /seo/referring-domains` */
  referringDomains(body: t.SeoReferringDomainsData['body'], options?: RequestOptions): Promise<t.SeoReferringDomainsResponses[keyof t.SeoReferringDomainsResponses]> {
    return this._client.request('POST', '/seo/referring-domains', { body, options });
  }

  /** Backlink anchors `POST /seo/backlink-anchors` */
  backlinkAnchors(body: t.SeoBacklinkAnchorsData['body'], options?: RequestOptions): Promise<t.SeoBacklinkAnchorsResponses[keyof t.SeoBacklinkAnchorsResponses]> {
    return this._client.request('POST', '/seo/backlink-anchors', { body, options });
  }

  /** Backlink spam score `POST /seo/spam-score` */
  spamScore(body: t.SeoSpamScoreData['body'], options?: RequestOptions): Promise<t.SeoSpamScoreResponses[keyof t.SeoSpamScoreResponses]> {
    return this._client.request('POST', '/seo/spam-score', { body, options });
  }

  /** Historical rank overview `POST /seo/rank-history` */
  rankHistory(body: t.SeoRankHistoryData['body'], options?: RequestOptions): Promise<t.SeoRankHistoryResponses[keyof t.SeoRankHistoryResponses]> {
    return this._client.request('POST', '/seo/rank-history', { body, options });
  }

  /** Deep site audit `POST /seo/site-audit` */
  siteAudit(body: t.SeoSiteAuditData['body'], options?: RequestOptions): Promise<t.SeoSiteAuditResponses[keyof t.SeoSiteAuditResponses]> {
    return this._client.request('POST', '/seo/site-audit', { body, options });
  }

  /** AI Visibility: brand lookup `POST /seo/brand-lookup` */
  brandLookup(body: t.SeoBrandLookupData['body'], options?: RequestOptions): Promise<t.SeoBrandLookupResponses[keyof t.SeoBrandLookupResponses]> {
    return this._client.request('POST', '/seo/brand-lookup', { body, options });
  }

  /** AI Visibility: prompt explorer `POST /seo/prompt-explorer` */
  promptExplorer(body: t.SeoPromptExplorerData['body'], options?: RequestOptions): Promise<t.SeoPromptExplorerResponses[keyof t.SeoPromptExplorerResponses]> {
    return this._client.request('POST', '/seo/prompt-explorer', { body, options });
  }

  /** AI Visibility Audit (async) `POST /seo/ai-audit` */
  aiAudit(body: t.SeoAiAuditData['body'], options?: RequestOptions): Promise<t.SeoAiAuditResponses[keyof t.SeoAiAuditResponses]> {
    return this._client.request('POST', '/seo/ai-audit', { body, options });
  }
}

/** Shorts endpoints. */
export class ShortsResource {
  constructor(private readonly _client: CoreClient) {}

  /** Generate viral shorts from a long video `POST /shorts/generate` */
  generate(body?: t.GenerateShortsData['body'], options?: RequestOptions): Promise<t.GenerateShortsResponses[keyof t.GenerateShortsResponses]> {
    return this._client.request('POST', '/shorts/generate', { body, options });
  }

  /** List shorts jobs `GET /shorts` */
  list(query?: t.ListShortsData['query'], options?: RequestOptions): Promise<t.ListShortsResponses[keyof t.ListShortsResponses]> {
    return this._client.request('GET', '/shorts', { query, options });
  }

  /** Get shorts job + clips `GET /shorts/{uid}` */
  get(uid: string, options?: RequestOptions): Promise<t.GetShortsResponses[keyof t.GetShortsResponses]> {
    return this._client.request('GET', `/shorts/${encodeURIComponent(uid)}`, { options });
  }
}

/** Social endpoints. */
export class SocialResource {
  constructor(private readonly _client: CoreClient) {}

  /** List social accounts `GET /social/accounts` */
  listAccounts(options?: RequestOptions): Promise<t.ListSocialAccountsResponses[keyof t.ListSocialAccountsResponses]> {
    return this._client.request('GET', '/social/accounts', { options });
  }

  /** List social posts `GET /social/posts` */
  listPosts(query?: t.ListSocialPostsData['query'], options?: RequestOptions): Promise<t.ListSocialPostsResponses[keyof t.ListSocialPostsResponses]> {
    return this._client.request('GET', '/social/posts', { query, options });
  }

  /** Create post (publish immediately) `POST /social/posts` */
  createPost(body: t.CreateSocialPostData['body'], options?: RequestOptions): Promise<t.CreateSocialPostResponses[keyof t.CreateSocialPostResponses]> {
    return this._client.request('POST', '/social/posts', { body, options });
  }

  /** Schedule post `POST /social/posts/schedule` */
  schedulePost(body: t.ScheduleSocialPostData['body'], options?: RequestOptions): Promise<t.ScheduleSocialPostResponses[keyof t.ScheduleSocialPostResponses]> {
    return this._client.request('POST', '/social/posts/schedule', { body, options });
  }

  /** Get social post `GET /social/posts/{post_id}` */
  getPost(postId: string, options?: RequestOptions): Promise<t.GetSocialPostResponses[keyof t.GetSocialPostResponses]> {
    return this._client.request('GET', `/social/posts/${encodeURIComponent(postId)}`, { options });
  }

  /** Update social post `PATCH /social/posts/{post_id}` */
  updatePost(postId: string, body: t.UpdateSocialPostData['body'], options?: RequestOptions): Promise<t.UpdateSocialPostResponses[keyof t.UpdateSocialPostResponses]> {
    return this._client.request('PATCH', `/social/posts/${encodeURIComponent(postId)}`, { body, options });
  }

  /** Delete social post `DELETE /social/posts/{post_id}` */
  deletePost(postId: string, options?: RequestOptions): Promise<t.DeleteSocialPostResponses[keyof t.DeleteSocialPostResponses]> {
    return this._client.request('DELETE', `/social/posts/${encodeURIComponent(postId)}`, { options });
  }

  /** Rename account `PATCH /social/accounts/{account_id}` */
  updateAccount(accountId: string, body: t.UpdateSocialAccountData['body'], options?: RequestOptions): Promise<t.UpdateSocialAccountResponses[keyof t.UpdateSocialAccountResponses]> {
    return this._client.request('PATCH', `/social/accounts/${encodeURIComponent(accountId)}`, { body, options });
  }

  /** Disconnect a social account `DELETE /social/accounts/{account_id}` */
  disconnectAccount(accountId: string, options?: RequestOptions): Promise<t.DisconnectSocialAccountResponses[keyof t.DisconnectSocialAccountResponses]> {
    return this._client.request('DELETE', `/social/accounts/${encodeURIComponent(accountId)}`, { options });
  }

  /** Account health `GET /social/accounts/{account_id}/health` */
  getAccountHealth(accountId: string, options?: RequestOptions): Promise<t.GetAccountHealthResponses[keyof t.GetAccountHealthResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/health`, { options });
  }

  /** Account reconnect URL `GET /social/accounts/{account_id}/reconnect-url` */
  getAccountReconnectUrl(accountId: string, options?: RequestOptions): Promise<t.GetAccountReconnectUrlResponses[keyof t.GetAccountReconnectUrlResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/reconnect-url`, { options });
  }

  /** Pause posting to an account `POST /social/accounts/{account_id}/pause` */
  pauseAccount(accountId: string, options?: RequestOptions): Promise<t.PauseSocialAccountResponses[keyof t.PauseSocialAccountResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/pause`, { options });
  }

  /** Resume posting to an account `POST /social/accounts/{account_id}/resume` */
  resumeAccount(accountId: string, options?: RequestOptions): Promise<t.ResumeSocialAccountResponses[keyof t.ResumeSocialAccountResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/resume`, { options });
  }

  /** Retry publishing a post `POST /social/posts/{post_id}/retry` */
  retryPost(postId: string, body: t.RetrySocialPostData['body'], options?: RequestOptions): Promise<t.RetrySocialPostResponses[keyof t.RetrySocialPostResponses]> {
    return this._client.request('POST', `/social/posts/${encodeURIComponent(postId)}/retry`, { body, options });
  }

  /** Poll headless connection status `GET /social/connect/{platform}` */
  connectAccountStatus(platform: string, options?: RequestOptions): Promise<t.ConnectSocialAccountStatusResponses[keyof t.ConnectSocialAccountStatusResponses]> {
    return this._client.request('GET', `/social/connect/${encodeURIComponent(platform)}`, { options });
  }

  /** Start headless account connection `POST /social/connect/{platform}` */
  connectAccount(platform: string, body?: t.ConnectSocialAccountData['body'], options?: RequestOptions): Promise<t.ConnectSocialAccountResponses[keyof t.ConnectSocialAccountResponses]> {
    return this._client.request('POST', `/social/connect/${encodeURIComponent(platform)}`, { body, options });
  }

  /** List queues `GET /social/queues` */
  listQueues(options?: RequestOptions): Promise<t.ListQueuesResponses[keyof t.ListQueuesResponses]> {
    return this._client.request('GET', '/social/queues', { options });
  }

  /** Create queue `POST /social/queues` */
  createQueue(body: t.CreateQueueData['body'], options?: RequestOptions): Promise<t.CreateQueueResponses[keyof t.CreateQueueResponses]> {
    return this._client.request('POST', '/social/queues', { body, options });
  }

  /** Get queue `GET /social/queues/{queue_id}` */
  getQueue(queueId: string, options?: RequestOptions): Promise<t.GetQueueResponses[keyof t.GetQueueResponses]> {
    return this._client.request('GET', `/social/queues/${encodeURIComponent(queueId)}`, { options });
  }

  /** Update queue `PUT /social/queues/{queue_id}` */
  updateQueue(queueId: string, body: t.UpdateQueueData['body'], options?: RequestOptions): Promise<t.UpdateQueueResponses[keyof t.UpdateQueueResponses]> {
    return this._client.request('PUT', `/social/queues/${encodeURIComponent(queueId)}`, { body, options });
  }

  /** Delete queue `DELETE /social/queues/{queue_id}` */
  deleteQueue(queueId: string, options?: RequestOptions): Promise<t.DeleteQueueResponses[keyof t.DeleteQueueResponses]> {
    return this._client.request('DELETE', `/social/queues/${encodeURIComponent(queueId)}`, { options });
  }

  /** Get next open slot `GET /social/queues/{queue_id}/next-slot` */
  getQueueNextSlot(queueId: string, options?: RequestOptions): Promise<t.GetQueueNextSlotResponses[keyof t.GetQueueNextSlotResponses]> {
    return this._client.request('GET', `/social/queues/${encodeURIComponent(queueId)}/next-slot`, { options });
  }

  /** Preview upcoming slots `GET /social/queues/{queue_id}/preview` */
  previewQueueSlots(queueId: string, query?: t.PreviewQueueSlotsData['query'], options?: RequestOptions): Promise<t.PreviewQueueSlotsResponses[keyof t.PreviewQueueSlotsResponses]> {
    return this._client.request('GET', `/social/queues/${encodeURIComponent(queueId)}/preview`, { query, options });
  }

  /** Unpublish post `POST /social/posts/{post_id}/unpublish` */
  unpublishPost(postId: string, body?: t.UnpublishPostData['body'], options?: RequestOptions): Promise<t.UnpublishPostResponses[keyof t.UnpublishPostResponses]> {
    return this._client.request('POST', `/social/posts/${encodeURIComponent(postId)}/unpublish`, { body, options });
  }

  /** Validate post content `POST /social/validate/post` */
  validatePost(body: t.ValidatePostData['body'], options?: RequestOptions): Promise<t.ValidatePostResponses[keyof t.ValidatePostResponses]> {
    return this._client.request('POST', '/social/validate/post', { body, options });
  }

  /** Validate media URL `POST /social/validate/media` */
  validateMedia(body: t.ValidateMediaData['body'], options?: RequestOptions): Promise<t.ValidateMediaResponses[keyof t.ValidateMediaResponses]> {
    return this._client.request('POST', '/social/validate/media', { body, options });
  }

  /** Stop recycling `DELETE /social/posts/{post_id}/recycle` */
  stopPostRecycle(postId: string, options?: RequestOptions): Promise<t.StopPostRecycleResponses[keyof t.StopPostRecycleResponses]> {
    return this._client.request('DELETE', `/social/posts/${encodeURIComponent(postId)}/recycle`, { options });
  }

  /** Bulk schedule posts `POST /social/posts/bulk` */
  bulkSchedulePosts(body: t.BulkSchedulePostsData['body'], options?: RequestOptions): Promise<t.BulkSchedulePostsResponses[keyof t.BulkSchedulePostsResponses]> {
    return this._client.request('POST', '/social/posts/bulk', { body, options });
  }

  /** Validate a bulk batch `POST /social/posts/bulk/validate` */
  validateBulkBatch(body: t.ValidateBulkBatchData['body'], options?: RequestOptions): Promise<t.ValidateBulkBatchResponses[keyof t.ValidateBulkBatchResponses]> {
    return this._client.request('POST', '/social/posts/bulk/validate', { body, options });
  }

  /** Bulk account health `GET /social/accounts/health` */
  bulkAccountHealth(options?: RequestOptions): Promise<t.BulkAccountHealthResponses[keyof t.BulkAccountHealthResponses]> {
    return this._client.request('GET', '/social/accounts/health', { options });
  }

  /** Follower stats `GET /social/accounts/follower-stats` */
  accountFollowerStats(query?: t.AccountFollowerStatsData['query'], options?: RequestOptions): Promise<t.AccountFollowerStatsResponses[keyof t.AccountFollowerStatsResponses]> {
    return this._client.request('GET', '/social/accounts/follower-stats', { query, options });
  }

  /** TikTok creator info `GET /social/accounts/{account_id}/tiktok/creator-info` */
  tiktokCreatorInfo(accountId: string, options?: RequestOptions): Promise<t.TiktokCreatorInfoResponses[keyof t.TiktokCreatorInfoResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/tiktok/creator-info`, { options });
  }

  /** Move account to profile `POST /social/accounts/{account_id}/move` */
  moveAccount(accountId: string, body: t.MoveSocialAccountData['body'], options?: RequestOptions): Promise<t.MoveSocialAccountResponses[keyof t.MoveSocialAccountResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/move`, { body, options });
  }

  /** List account groups `GET /social/account-groups` */
  listAccountGroups(options?: RequestOptions): Promise<t.ListAccountGroupsResponses[keyof t.ListAccountGroupsResponses]> {
    return this._client.request('GET', '/social/account-groups', { options });
  }

  /** Create account group `POST /social/account-groups` */
  createAccountGroup(body: t.CreateAccountGroupData['body'], options?: RequestOptions): Promise<t.CreateAccountGroupResponses[keyof t.CreateAccountGroupResponses]> {
    return this._client.request('POST', '/social/account-groups', { body, options });
  }

  /** Get account group `GET /social/account-groups/{group_id}` */
  getAccountGroup(groupId: string, options?: RequestOptions): Promise<t.GetAccountGroupResponses[keyof t.GetAccountGroupResponses]> {
    return this._client.request('GET', `/social/account-groups/${encodeURIComponent(groupId)}`, { options });
  }

  /** Update account group `PUT /social/account-groups/{group_id}` */
  updateAccountGroup(groupId: string, body: t.UpdateAccountGroupData['body'], options?: RequestOptions): Promise<t.UpdateAccountGroupResponses[keyof t.UpdateAccountGroupResponses]> {
    return this._client.request('PUT', `/social/account-groups/${encodeURIComponent(groupId)}`, { body, options });
  }

  /** Delete account group `DELETE /social/account-groups/{group_id}` */
  deleteAccountGroup(groupId: string, options?: RequestOptions): Promise<t.DeleteAccountGroupResponses[keyof t.DeleteAccountGroupResponses]> {
    return this._client.request('DELETE', `/social/account-groups/${encodeURIComponent(groupId)}`, { options });
  }

  /** Get conversation `GET /social/conversations/{conversation_id}` */
  getConversation(conversationId: string, options?: RequestOptions): Promise<t.GetConversationResponses[keyof t.GetConversationResponses]> {
    return this._client.request('GET', `/social/conversations/${encodeURIComponent(conversationId)}`, { options });
  }

  /** Archive / reopen conversation `PATCH /social/conversations/{conversation_id}` */
  updateConversation(conversationId: string, body: t.UpdateConversationData['body'], options?: RequestOptions): Promise<t.UpdateConversationResponses[keyof t.UpdateConversationResponses]> {
    return this._client.request('PATCH', `/social/conversations/${encodeURIComponent(conversationId)}`, { body, options });
  }

  /** Search conversations `GET /social/conversations/search` */
  searchConversations(query?: t.SearchConversationsData['query'], options?: RequestOptions): Promise<t.SearchConversationsResponses[keyof t.SearchConversationsResponses]> {
    return this._client.request('GET', '/social/conversations/search', { query, options });
  }

  /** Pinterest boards `GET /social/accounts/{account_id}/pinterest/boards` */
  pinterestBoards(accountId: string, options?: RequestOptions): Promise<t.PinterestBoardsResponses[keyof t.PinterestBoardsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/pinterest/boards`, { options });
  }

  /** YouTube playlists `GET /social/accounts/{account_id}/youtube/playlists` */
  youtubePlaylists(accountId: string, options?: RequestOptions): Promise<t.YoutubePlaylistsResponses[keyof t.YoutubePlaylistsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/youtube/playlists`, { options });
  }

  /** Instagram publishing limit `GET /social/accounts/{account_id}/instagram/publishing-limit` */
  instagramPublishingLimit(accountId: string, options?: RequestOptions): Promise<t.InstagramPublishingLimitResponses[keyof t.InstagramPublishingLimitResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/instagram/publishing-limit`, { options });
  }

  /** Google Business performance `GET /social/accounts/{account_id}/gmb/performance` */
  gmbPerformance(accountId: string, query?: t.GmbPerformanceData['query'], options?: RequestOptions): Promise<t.GmbPerformanceResponses[keyof t.GmbPerformanceResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/performance`, { query, options });
  }

  /** Google Business search keywords `GET /social/accounts/{account_id}/gmb/search-keywords` */
  gmbSearchKeywords(accountId: string, query?: t.GmbSearchKeywordsData['query'], options?: RequestOptions): Promise<t.GmbSearchKeywordsResponses[keyof t.GmbSearchKeywordsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/search-keywords`, { query, options });
  }

  /** Reddit search `GET /social/accounts/{account_id}/reddit/search` */
  redditSearch(accountId: string, query?: t.RedditSearchData['query'], options?: RequestOptions): Promise<t.RedditSearchResponses[keyof t.RedditSearchResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/reddit/search`, { query, options });
  }

  /** Reddit feed `GET /social/accounts/{account_id}/reddit/feed` */
  redditFeed(accountId: string, query?: t.RedditFeedData['query'], options?: RequestOptions): Promise<t.RedditFeedResponses[keyof t.RedditFeedResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/reddit/feed`, { query, options });
  }

  /** Subscribed subreddits `GET /social/accounts/{account_id}/reddit/subreddits` */
  redditSubreddits(accountId: string, options?: RequestOptions): Promise<t.RedditSubredditsResponses[keyof t.RedditSubredditsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/reddit/subreddits`, { options });
  }

  /** Subreddit rules `GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}/rules` */
  redditSubredditRules(accountId: string, subreddit: string, options?: RequestOptions): Promise<t.RedditSubredditRulesResponses[keyof t.RedditSubredditRulesResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/reddit/subreddits/${encodeURIComponent(subreddit)}/rules`, { options });
  }

  /** Instagram stories `GET /social/accounts/{account_id}/instagram/stories` */
  instagramStories(accountId: string, options?: RequestOptions): Promise<t.InstagramStoriesResponses[keyof t.InstagramStoriesResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/instagram/stories`, { options });
  }

  /** Facebook post reactions `GET /social/accounts/{account_id}/facebook/post-reactions` */
  facebookPostReactions(accountId: string, query?: t.FacebookPostReactionsData['query'], options?: RequestOptions): Promise<t.FacebookPostReactionsResponses[keyof t.FacebookPostReactionsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/facebook/post-reactions`, { query, options });
  }

  /** Instagram story insights `GET /social/accounts/{account_id}/instagram/stories/{story_id}/insights` */
  instagramStoryInsights(accountId: string, storyId: string, query?: t.InstagramStoryInsightsData['query'], options?: RequestOptions): Promise<t.InstagramStoryInsightsResponses[keyof t.InstagramStoryInsightsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/instagram/stories/${encodeURIComponent(storyId)}/insights`, { query, options });
  }

  /** Retweet on X `POST /social/accounts/{account_id}/x/retweets` */
  xRetweet(accountId: string, body: t.XRetweetData['body'], options?: RequestOptions): Promise<t.XRetweetResponses[keyof t.XRetweetResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/x/retweets`, { body, options });
  }

  /** Undo retweet `DELETE /social/accounts/{account_id}/x/retweets/{tweet_id}` */
  xUnretweet(accountId: string, tweetId: string, options?: RequestOptions): Promise<t.XUnretweetResponses[keyof t.XUnretweetResponses]> {
    return this._client.request('DELETE', `/social/accounts/${encodeURIComponent(accountId)}/x/retweets/${encodeURIComponent(tweetId)}`, { options });
  }

  /** Edit published post `POST /social/posts/{post_id}/edit` */
  editPublishedPost(postId: string, body: t.EditPublishedPostData['body'], options?: RequestOptions): Promise<t.EditPublishedPostResponses[keyof t.EditPublishedPostResponses]> {
    return this._client.request('POST', `/social/posts/${encodeURIComponent(postId)}/edit`, { body, options });
  }

  /** Update YouTube metadata `POST /social/posts/{post_id}/update-metadata` */
  updatePostMetadata(postId: string, body: t.UpdatePostMetadataData['body'], options?: RequestOptions): Promise<t.UpdatePostMetadataResponses[keyof t.UpdatePostMetadataResponses]> {
    return this._client.request('POST', `/social/posts/${encodeURIComponent(postId)}/update-metadata`, { body, options });
  }

  /** Sync external posts `POST /social/posts/sync-external` */
  syncExternalPosts(body: t.SyncExternalPostsData['body'], options?: RequestOptions): Promise<t.SyncExternalPostsResponses[keyof t.SyncExternalPostsResponses]> {
    return this._client.request('POST', '/social/posts/sync-external', { body, options });
  }

  /** Live account insights `GET /social/accounts/{account_id}/insights` */
  accountInsights(accountId: string, options?: RequestOptions): Promise<t.AccountInsightsResponses[keyof t.AccountInsightsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/insights`, { options });
  }

  /** List Google locations `GET /social/accounts/{account_id}/gmb/locations` */
  gmbLocations(accountId: string, query?: t.GmbLocationsData['query'], options?: RequestOptions): Promise<t.GmbLocationsResponses[keyof t.GmbLocationsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/locations`, { query, options });
  }

  /** Get business info `GET /social/accounts/{account_id}/gmb/location` */
  gmbLocation(accountId: string, query?: t.GmbLocationData['query'], options?: RequestOptions): Promise<t.GmbLocationResponses[keyof t.GmbLocationResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/location`, { query, options });
  }

  /** Update business info `PATCH /social/accounts/{account_id}/gmb/location` */
  gmbUpdateLocation(accountId: string, body: t.GmbUpdateLocationData['body'], options?: RequestOptions): Promise<t.GmbUpdateLocationResponses[keyof t.GmbUpdateLocationResponses]> {
    return this._client.request('PATCH', `/social/accounts/${encodeURIComponent(accountId)}/gmb/location`, { body, options });
  }

  /** Get attributes `GET /social/accounts/{account_id}/gmb/attributes` */
  gmbAttributes(accountId: string, options?: RequestOptions): Promise<t.GmbAttributesResponses[keyof t.GmbAttributesResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/attributes`, { options });
  }

  /** Update attributes `PUT /social/accounts/{account_id}/gmb/attributes` */
  gmbUpdateAttributes(accountId: string, body: t.GmbUpdateAttributesData['body'], options?: RequestOptions): Promise<t.GmbUpdateAttributesResponses[keyof t.GmbUpdateAttributesResponses]> {
    return this._client.request('PUT', `/social/accounts/${encodeURIComponent(accountId)}/gmb/attributes`, { body, options });
  }

  /** Available attributes `GET /social/accounts/{account_id}/gmb/attributes/metadata` */
  gmbAttributeMetadata(accountId: string, options?: RequestOptions): Promise<t.GmbAttributeMetadataResponses[keyof t.GmbAttributeMetadataResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/attributes/metadata`, { options });
  }

  /** List media `GET /social/accounts/{account_id}/gmb/media` */
  gmbMedia(accountId: string, options?: RequestOptions): Promise<t.GmbMediaResponses[keyof t.GmbMediaResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/media`, { options });
  }

  /** Add photo `POST /social/accounts/{account_id}/gmb/media` */
  gmbCreateMedia(accountId: string, body: t.GmbCreateMediaData['body'], options?: RequestOptions): Promise<t.GmbCreateMediaResponses[keyof t.GmbCreateMediaResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/gmb/media`, { body, options });
  }

  /** Delete media `DELETE /social/accounts/{account_id}/gmb/media` */
  gmbDeleteMedia(accountId: string, body: t.GmbDeleteMediaData['body'], options?: RequestOptions): Promise<t.GmbDeleteMediaResponses[keyof t.GmbDeleteMediaResponses]> {
    return this._client.request('DELETE', `/social/accounts/${encodeURIComponent(accountId)}/gmb/media`, { body, options });
  }

  /** Get food menus `GET /social/accounts/{account_id}/gmb/food-menus` */
  gmbFoodMenus(accountId: string, options?: RequestOptions): Promise<t.GmbFoodMenusResponses[keyof t.GmbFoodMenusResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/food-menus`, { options });
  }

  /** Update food menus `PUT /social/accounts/{account_id}/gmb/food-menus` */
  gmbUpdateFoodMenus(accountId: string, body: t.GmbUpdateFoodMenusData['body'], options?: RequestOptions): Promise<t.GmbUpdateFoodMenusResponses[keyof t.GmbUpdateFoodMenusResponses]> {
    return this._client.request('PUT', `/social/accounts/${encodeURIComponent(accountId)}/gmb/food-menus`, { body, options });
  }

  /** List place-action links `GET /social/accounts/{account_id}/gmb/place-actions` */
  gmbPlaceActions(accountId: string, options?: RequestOptions): Promise<t.GmbPlaceActionsResponses[keyof t.GmbPlaceActionsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/place-actions`, { options });
  }

  /** Create place-action link `POST /social/accounts/{account_id}/gmb/place-actions` */
  gmbCreatePlaceAction(accountId: string, body: t.GmbCreatePlaceActionData['body'], options?: RequestOptions): Promise<t.GmbCreatePlaceActionResponses[keyof t.GmbCreatePlaceActionResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/gmb/place-actions`, { body, options });
  }

  /** Update place-action link `PATCH /social/accounts/{account_id}/gmb/place-actions` */
  gmbUpdatePlaceAction(accountId: string, body: t.GmbUpdatePlaceActionData['body'], options?: RequestOptions): Promise<t.GmbUpdatePlaceActionResponses[keyof t.GmbUpdatePlaceActionResponses]> {
    return this._client.request('PATCH', `/social/accounts/${encodeURIComponent(accountId)}/gmb/place-actions`, { body, options });
  }

  /** Delete place-action link `DELETE /social/accounts/{account_id}/gmb/place-actions` */
  gmbDeletePlaceAction(accountId: string, body: t.GmbDeletePlaceActionData['body'], options?: RequestOptions): Promise<t.GmbDeletePlaceActionResponses[keyof t.GmbDeletePlaceActionResponses]> {
    return this._client.request('DELETE', `/social/accounts/${encodeURIComponent(accountId)}/gmb/place-actions`, { body, options });
  }

  /** List verifications `GET /social/accounts/{account_id}/gmb/verifications` */
  gmbVerifications(accountId: string, options?: RequestOptions): Promise<t.GmbVerificationsResponses[keyof t.GmbVerificationsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/gmb/verifications`, { options });
  }

  /** Verification options `POST /social/accounts/{account_id}/gmb/verifications/options` */
  gmbVerificationOptions(accountId: string, body?: t.GmbVerificationOptionsData['body'], options?: RequestOptions): Promise<t.GmbVerificationOptionsResponses[keyof t.GmbVerificationOptionsResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/gmb/verifications/options`, { body, options });
  }

  /** Subreddit info + eligibility `GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}` */
  redditSubredditInfo(accountId: string, subreddit: string, options?: RequestOptions): Promise<t.RedditSubredditInfoResponses[keyof t.RedditSubredditInfoResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/reddit/subreddits/${encodeURIComponent(subreddit)}`, { options });
  }

  /** X mentions `GET /social/accounts/{account_id}/x/mentions` */
  xMentions(accountId: string, query?: t.XMentionsData['query'], options?: RequestOptions): Promise<t.XMentionsResponses[keyof t.XMentionsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/x/mentions`, { query, options });
  }

  /** Typing indicator `POST /social/conversations/{conversation_id}/typing` */
  sendTypingIndicator(conversationId: string, options?: RequestOptions): Promise<t.SendTypingIndicatorResponses[keyof t.SendTypingIndicatorResponses]> {
    return this._client.request('POST', `/social/conversations/${encodeURIComponent(conversationId)}/typing`, { options });
  }

  /** Private reply (comment-to-DM) `POST /social/comments/{comment_id}/private-reply` */
  commentPrivateReply(commentId: string, body: t.CommentPrivateReplyData['body'], options?: RequestOptions): Promise<t.CommentPrivateReplyResponses[keyof t.CommentPrivateReplyResponses]> {
    return this._client.request('POST', `/social/comments/${encodeURIComponent(commentId)}/private-reply`, { body, options });
  }

  /** Get Messenger menu `GET /social/accounts/{account_id}/messenger/menu` */
  getMessengerMenu(accountId: string, options?: RequestOptions): Promise<t.GetMessengerMenuResponses[keyof t.GetMessengerMenuResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/messenger/menu`, { options });
  }

  /** Set Messenger menu `PUT /social/accounts/{account_id}/messenger/menu` */
  setMessengerMenu(accountId: string, body: t.SetMessengerMenuData['body'], options?: RequestOptions): Promise<t.SetMessengerMenuResponses[keyof t.SetMessengerMenuResponses]> {
    return this._client.request('PUT', `/social/accounts/${encodeURIComponent(accountId)}/messenger/menu`, { body, options });
  }

  /** Delete Messenger menu `DELETE /social/accounts/{account_id}/messenger/menu` */
  deleteMessengerMenu(accountId: string, options?: RequestOptions): Promise<t.DeleteMessengerMenuResponses[keyof t.DeleteMessengerMenuResponses]> {
    return this._client.request('DELETE', `/social/accounts/${encodeURIComponent(accountId)}/messenger/menu`, { options });
  }

  /** Get ice breakers `GET /social/accounts/{account_id}/instagram/ice-breakers` */
  getIceBreakers(accountId: string, options?: RequestOptions): Promise<t.GetIceBreakersResponses[keyof t.GetIceBreakersResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/instagram/ice-breakers`, { options });
  }

  /** Set ice breakers `PUT /social/accounts/{account_id}/instagram/ice-breakers` */
  setIceBreakers(accountId: string, body: t.SetIceBreakersData['body'], options?: RequestOptions): Promise<t.SetIceBreakersResponses[keyof t.SetIceBreakersResponses]> {
    return this._client.request('PUT', `/social/accounts/${encodeURIComponent(accountId)}/instagram/ice-breakers`, { body, options });
  }

  /** Delete ice breakers `DELETE /social/accounts/{account_id}/instagram/ice-breakers` */
  deleteIceBreakers(accountId: string, options?: RequestOptions): Promise<t.DeleteIceBreakersResponses[keyof t.DeleteIceBreakersResponses]> {
    return this._client.request('DELETE', `/social/accounts/${encodeURIComponent(accountId)}/instagram/ice-breakers`, { options });
  }

  /** Facebook page insights `GET /social/accounts/{account_id}/facebook/page-insights` */
  facebookPageInsights(accountId: string, query?: t.FacebookPageInsightsData['query'], options?: RequestOptions): Promise<t.FacebookPageInsightsResponses[keyof t.FacebookPageInsightsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/facebook/page-insights`, { query, options });
  }

  /** Instagram audience demographics `GET /social/accounts/{account_id}/instagram/audience` */
  instagramAudience(accountId: string, query?: t.InstagramAudienceData['query'], options?: RequestOptions): Promise<t.InstagramAudienceResponses[keyof t.InstagramAudienceResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/instagram/audience`, { query, options });
  }

  /** Connection target options `GET /social/accounts/{account_id}/connect-options` */
  connectOptions(accountId: string, options?: RequestOptions): Promise<t.ConnectOptionsResponses[keyof t.ConnectOptionsResponses]> {
    return this._client.request('GET', `/social/accounts/${encodeURIComponent(accountId)}/connect-options`, { options });
  }

  /** Select connection target `POST /social/accounts/{account_id}/connect-select` */
  connectSelect(accountId: string, body: t.ConnectSelectData['body'], options?: RequestOptions): Promise<t.ConnectSelectResponses[keyof t.ConnectSelectResponses]> {
    return this._client.request('POST', `/social/accounts/${encodeURIComponent(accountId)}/connect-select`, { body, options });
  }
}

/** URLs endpoints. */
export class UrlsResource {
  constructor(private readonly _client: CoreClient) {}

  /** Shorten URL `POST /urls/shorten` */
  shorten(body: t.ShortenUrlData['body'], options?: RequestOptions): Promise<t.ShortenUrlResponses[keyof t.ShortenUrlResponses]> {
    return this._client.request('POST', '/urls/shorten', { body, options });
  }

  /** List short URLs `GET /urls` */
  list(query?: t.ListUrlsData['query'], options?: RequestOptions): Promise<t.ListUrlsResponses[keyof t.ListUrlsResponses]> {
    return this._client.request('GET', '/urls', { query, options });
  }

  /** Get short URL `GET /urls/{url_id}` */
  get(urlId: string, options?: RequestOptions): Promise<t.GetUrlResponses[keyof t.GetUrlResponses]> {
    return this._client.request('GET', `/urls/${encodeURIComponent(urlId)}`, { options });
  }

  /** Delete short URL `DELETE /urls/{url_id}` */
  delete(urlId: string, options?: RequestOptions): Promise<t.DeleteUrlResponses[keyof t.DeleteUrlResponses]> {
    return this._client.request('DELETE', `/urls/${encodeURIComponent(urlId)}`, { options });
  }

  /** Get short URL stats `GET /urls/{url_id}/stats` */
  getStats(urlId: string, options?: RequestOptions): Promise<t.GetUrlStatsResponses[keyof t.GetUrlStatsResponses]> {
    return this._client.request('GET', `/urls/${encodeURIComponent(urlId)}/stats`, { options });
  }
}

/** Videos endpoints. */
export class VideosResource {
  constructor(private readonly _client: CoreClient) {}

  /** List available video models `GET /videos/models` */
  listModels(options?: RequestOptions): Promise<t.ListVideoModelsResponses[keyof t.ListVideoModelsResponses]> {
    return this._client.request('GET', '/videos/models', { options });
  }

  /** Generate video `POST /videos/generate` */
  generate(body: t.GenerateVideoData['body'], options?: RequestOptions): Promise<t.GenerateVideoResponses[keyof t.GenerateVideoResponses]> {
    return this._client.request('POST', '/videos/generate', { body, options });
  }

  /** List videos `GET /videos` */
  list(query?: t.ListVideosData['query'], options?: RequestOptions): Promise<t.ListVideosResponses[keyof t.ListVideosResponses]> {
    return this._client.request('GET', '/videos', { query, options });
  }

  /** Get video `GET /videos/{video_id}` */
  get(videoId: string, options?: RequestOptions): Promise<t.GetVideoResponses[keyof t.GetVideoResponses]> {
    return this._client.request('GET', `/videos/${encodeURIComponent(videoId)}`, { options });
  }

  /** Delete video `DELETE /videos/{video_id}` */
  delete(videoId: string, options?: RequestOptions): Promise<t.DeleteVideoResponses[keyof t.DeleteVideoResponses]> {
    return this._client.request('DELETE', `/videos/${encodeURIComponent(videoId)}`, { options });
  }

  /** Generate a viral hook line `POST /videos/hook` */
  generateHook(body?: t.GenerateVideoHookData['body'], options?: RequestOptions): Promise<t.GenerateVideoHookResponses[keyof t.GenerateVideoHookResponses]> {
    return this._client.request('POST', '/videos/hook', { body, options });
  }

  /** Suggest B-roll moments `POST /videos/broll-suggest` */
  suggestBroll(body: t.SuggestBrollData['body'], options?: RequestOptions): Promise<t.SuggestBrollResponses[keyof t.SuggestBrollResponses]> {
    return this._client.request('POST', '/videos/broll-suggest', { body, options });
  }

  /** Suggest on-screen emphasis `POST /videos/emphasis` */
  suggestEmphasis(body: t.SuggestEmphasisData['body'], options?: RequestOptions): Promise<t.SuggestEmphasisResponses[keyof t.SuggestEmphasisResponses]> {
    return this._client.request('POST', '/videos/emphasis', { body, options });
  }

  /** Generate a viral thumbnail `POST /videos/viral-thumbnail` */
  generateViralThumbnail(body: t.GenerateViralThumbnailData['body'], options?: RequestOptions): Promise<t.GenerateViralThumbnailResponses[keyof t.GenerateViralThumbnailResponses]> {
    return this._client.request('POST', '/videos/viral-thumbnail', { body, options });
  }
}

/** Webhooks endpoints. */
export class WebhooksResource {
  constructor(private readonly _client: CoreClient) {}

  /** List webhooks `GET /webhooks` */
  list(options?: RequestOptions): Promise<t.ListWebhooksResponses[keyof t.ListWebhooksResponses]> {
    return this._client.request('GET', '/webhooks', { options });
  }

  /** Create webhook `POST /webhooks` */
  create(body: t.CreateWebhookData['body'], options?: RequestOptions): Promise<t.CreateWebhookResponses[keyof t.CreateWebhookResponses]> {
    return this._client.request('POST', '/webhooks', { body, options });
  }

  /** Update webhook `PUT /webhooks/{id}` */
  update(id: string, body: t.UpdateWebhookData['body'], options?: RequestOptions): Promise<t.UpdateWebhookResponses[keyof t.UpdateWebhookResponses]> {
    return this._client.request('PUT', `/webhooks/${encodeURIComponent(id)}`, { body, options });
  }

  /** Delete webhook `DELETE /webhooks/{id}` */
  delete(id: string, options?: RequestOptions): Promise<t.DeleteWebhookResponses[keyof t.DeleteWebhookResponses]> {
    return this._client.request('DELETE', `/webhooks/${encodeURIComponent(id)}`, { options });
  }

  /** List webhook delivery logs `GET /webhooks/logs` */
  listLogs(query?: t.ListWebhookLogsData['query'], options?: RequestOptions): Promise<t.ListWebhookLogsResponses[keyof t.ListWebhookLogsResponses]> {
    return this._client.request('GET', '/webhooks/logs', { query, options });
  }

  /** Send test webhook `POST /webhooks/{id}/test` */
  test(id: string, options?: RequestOptions): Promise<t.TestWebhookResponses[keyof t.TestWebhookResponses]> {
    return this._client.request('POST', `/webhooks/${encodeURIComponent(id)}/test`, { options });
  }
}

/** Workspaces endpoints. */
export class WorkspacesResource {
  constructor(private readonly _client: CoreClient) {}

  /** List workspaces (sub-accounts) `GET /workspaces` */
  list(options?: RequestOptions): Promise<t.ListWorkspacesResponses[keyof t.ListWorkspacesResponses]> {
    return this._client.request('GET', '/workspaces', { options });
  }

  /** Create a workspace (sub-account) `POST /workspaces` */
  create(body: t.CreateWorkspaceData['body'], options?: RequestOptions): Promise<t.CreateWorkspaceResponses[keyof t.CreateWorkspaceResponses]> {
    return this._client.request('POST', '/workspaces', { body, options });
  }

  /** Bulk sub-account action `POST /workspaces/bulk` */
  bulkAction(body: t.BulkWorkspaceActionData['body'], options?: RequestOptions): Promise<t.BulkWorkspaceActionResponses[keyof t.BulkWorkspaceActionResponses]> {
    return this._client.request('POST', '/workspaces/bulk', { body, options });
  }

  /** Get a workspace (sub-account) `GET /workspaces/{id}` */
  get(id: string, options?: RequestOptions): Promise<t.GetWorkspaceResponses[keyof t.GetWorkspaceResponses]> {
    return this._client.request('GET', `/workspaces/${encodeURIComponent(id)}`, { options });
  }

  /** Delete a workspace (sub-account) `DELETE /workspaces/{id}` */
  delete(id: string, body: t.DeleteWorkspaceData['body'], options?: RequestOptions): Promise<t.DeleteWorkspaceResponses[keyof t.DeleteWorkspaceResponses]> {
    return this._client.request('DELETE', `/workspaces/${encodeURIComponent(id)}`, { body, options });
  }

  /** Disable SaaS mode for a workspace `POST /workspaces/{id}/disable-saas` */
  disableSaas(id: string, body?: t.DisableWorkspaceSaasData['body'], options?: RequestOptions): Promise<t.DisableWorkspaceSaasResponses[keyof t.DisableWorkspaceSaasResponses]> {
    return this._client.request('POST', `/workspaces/${encodeURIComponent(id)}/disable-saas`, { body, options });
  }

  /** Pause (suspend) a workspace `POST /workspaces/{id}/pause` */
  pause(id: string, options?: RequestOptions): Promise<t.PauseWorkspaceResponses[keyof t.PauseWorkspaceResponses]> {
    return this._client.request('POST', `/workspaces/${encodeURIComponent(id)}/pause`, { options });
  }

  /** Resume a paused workspace `POST /workspaces/{id}/resume` */
  resume(id: string, options?: RequestOptions): Promise<t.ResumeWorkspaceResponses[keyof t.ResumeWorkspaceResponses]> {
    return this._client.request('POST', `/workspaces/${encodeURIComponent(id)}/resume`, { options });
  }

  /** Get a sub-account's subscription `GET /workspaces/{id}/subscription` */
  getSubscription(id: string, options?: RequestOptions): Promise<t.GetWorkspaceSubscriptionResponses[keyof t.GetWorkspaceSubscriptionResponses]> {
    return this._client.request('GET', `/workspaces/${encodeURIComponent(id)}/subscription`, { options });
  }

  /** Get a sub-account's wallet balance `GET /workspaces/{id}/wallet` */
  getWallet(id: string, options?: RequestOptions): Promise<t.GetWorkspaceWalletResponses[keyof t.GetWorkspaceWalletResponses]> {
    return this._client.request('GET', `/workspaces/${encodeURIComponent(id)}/wallet`, { options });
  }

  /** List SaaS plans `GET /saas/plans` */
  listSaasPlans(options?: RequestOptions): Promise<t.ListSaasPlansResponses[keyof t.ListSaasPlansResponses]> {
    return this._client.request('GET', '/saas/plans', { options });
  }

  /** Get a SaaS plan `GET /saas/plans/{id}` */
  getSaasPlan(id: string, options?: RequestOptions): Promise<t.GetSaasPlanResponses[keyof t.GetSaasPlanResponses]> {
    return this._client.request('GET', `/saas/plans/${encodeURIComponent(id)}`, { options });
  }
}

export function createResources(client: CoreClient) {
  return {
    account: new AccountResource(client),
    captain: new CaptainResource(client),
    analytics: new AnalyticsResource(client),
    articles: new ArticlesResource(client),
    audio: new AudioResource(client),
    automations: new AutomationsResource(client),
    chatbots: new ChatbotsResource(client),
    comments: new CommentsResource(client),
    content: new ContentResource(client),
    crm: new CrmResource(client),
    contacts: new ContactsResource(client),
    customFields: new CustomFieldsResource(client),
    opportunities: new OpportunitiesResource(client),
    messages: new MessagesResource(client),
    images: new ImagesResource(client),
    jobs: new JobsResource(client),
    media: new MediaResource(client),
    presentations: new PresentationsResource(client),
    profiles: new ProfilesResource(client),
    reviews: new ReviewsResource(client),
    seo: new SeoResource(client),
    shorts: new ShortsResource(client),
    social: new SocialResource(client),
    urls: new UrlsResource(client),
    videos: new VideosResource(client),
    webhooks: new WebhooksResource(client),
    workspaces: new WorkspacesResource(client),
  };
}
